Repository prgrms-web-devcourse-final-project/WEB3_4_8BIT_BE, pull requests merged in 2025-04, with the labels that each got.

#21 MIKKI-82
  backend/src/main/java/com/backend/domain/captain/controller/CaptainController.java
  backend/src/main/java/com/backend/domain/captain/dto/Request/CaptainRequest.java
  backend/src/main/java/com/backend/domain/captain/dto/Response/CaptainResponse.java
  backend/src/main/java/com/backend/domain/captain/repository/CaptainQueryRepository.java
  backend/src/main/java/com/backend/domain/captain/repository/CaptainRepository.java
  backend/src/main/java/com/backend/domain/captain/repository/CaptainRepositoryImpl.java
  backend/src/main/java/com/backend/domain/captain/service/CaptainService.java
  backend/src/main/java/com/backend/domain/captain/service/CaptainServiceImpl.java
  backend/src/test/java/com/backend/domain/captain/controller/CaptainControllerTest.java
  backend/src/test/java/com/backend/domain/captain/repository/CaptainRepositoryTest.java
  backend/src/test/java/com/backend/domain/captain/service/CaptainServiceTest.java
Labels: enhancement

#23 MIKKI-83
  backend/src/main/java/com/backend/domain/auth/controller/AuthController.java
  backend/src/main/java/com/backend/domain/captain/controller/CaptainController.java
  backend/src/main/java/com/backend/domain/fishencyclopedia/controller/FishEncyclopediaController.java
  backend/src/main/java/com/backend/domain/fishencyclopedia/repository/FishEncyclopediaQueryRepository.java
  backend/src/main/java/com/backend/domain/fishencyclopedia/repository/FishEncyclopediaRepository.java
  backend/src/main/java/com/backend/domain/fishencyclopedia/repository/FishEncyclopediaRepositoryImpl.java
  backend/src/main/java/com/backend/domain/fishencyclopedia/service/FishEncyclopediaService.java
  backend/src/main/java/com/backend/domain/fishencyclopedia/service/FishEncyclopediaServiceImpl.java
  backend/src/main/java/com/backend/domain/member/controller/MemberController.java
  backend/src/main/java/com/backend/domain/review/controller/ReviewController.java
  backend/src/main/java/com/backend/domain/review/dto/response/ReviewWithMemberResponse.java
  backend/src/main/java/com/backend/domain/review/exception/ReviewErrorCode.java
  backend/src/main/java/com/backend/domain/review/repository/ReviewJpaRepository.java
  backend/src/main/java/com/backend/domain/review/repository/ReviewRepository.java
  backend/src/main/java/com/backend/domain/review/repository/ReviewRepositoryImpl.java
  backend/src/main/java/com/backend/domain/review/service/ReviewService.java
  backend/src/main/java/com/backend/domain/review/service/ReviewServiceImpl.java
  backend/src/main/java/com/backend/domain/shipfishingpost/controller/ShipFishingPostController.java
  backend/src/main/java/com/backend/global/advice/GlobalControllerAdvice.java
  backend/src/main/java/com/backend/global/auth/oauth2/handler/OAuth2AuthenticationFailureHandler.java
  backend/src/main/java/com/backend/global/auth/oauth2/handler/OAuth2AuthenticationSuccessHandler.java
  backend/src/main/java/com/backend/global/dto/request/GlobalRequest.java
  backend/src/main/java/com/backend/global/dto/response/ErrorDetail.java
  backend/src/main/java/com/backend/global/dto/response/GenericResponse.java
  backend/src/main/java/com/backend/global/dto/response/ScrollResponse.java
  backend/src/main/java/com/backend/global/storage/controller/StorageController.java
  backend/src/main/java/com/backend/global/util/AuthResponseUtil.java
  backend/src/test/java/com/backend/domain/fishencyclopedia/controller/FishEncyclopediaControllerTest.java
  backend/src/test/java/com/backend/domain/fishencyclopedia/dto/request/FishEncyclopediaRequestTest.java
  backend/src/test/java/com/backend/domain/fishencyclopedia/repository/FishEncyclopediaRepositoryTest.java
  backend/src/test/java/com/backend/domain/fishencyclopedia/service/FishEncyclopediaServiceTest.java
  backend/src/test/java/com/backend/domain/review/controller/ReviewControllerTest.java
  backend/src/test/java/com/backend/domain/review/repository/ReviewRepositoryTest.java
  backend/src/test/java/com/backend/domain/review/service/ReviewServiceTest.java
Labels: enhancement

#22 MIKKI-91
  backend/src/main/java/com/backend/domain/captain/controller/CaptainController.java
  backend/src/main/java/com/backend/domain/captain/dto/Request/CaptainRequest.java
  backend/src/main/java/com/backend/domain/captain/entity/Captain.java
  backend/src/main/java/com/backend/domain/captain/service/CaptainService.java
  backend/src/main/java/com/backend/domain/captain/service/CaptainServiceImpl.java
  backend/src/main/java/com/backend/domain/member/controller/MemberController.java
  backend/src/main/java/com/backend/global/auth/oauth2/handler/OAuth2AuthenticationSuccessHandler.java
  backend/src/test/java/com/backend/domain/captain/controller/CaptainControllerTest.java
  backend/src/test/java/com/backend/domain/captain/service/CaptainServiceTest.java
  backend/src/test/java/com/backend/domain/member/controller/MemberControllerTest.java
Labels: enhancement

#20 MIKKI-78
  backend/src/main/java/com/backend/domain/fish/exception/FishErrorCode.java
  backend/src/main/java/com/backend/domain/fish/exception/FishException.java
  backend/src/main/java/com/backend/domain/fish/repository/FishRepository.java
  backend/src/main/java/com/backend/domain/fish/repository/FishRepositoryImpl.java
  backend/src/main/java/com/backend/domain/shipfishingpost/controller/ShipFishingPostController.java
  backend/src/main/java/com/backend/domain/shipfishingpost/dto/request/ShipFishingPostRequest.java
  backend/src/main/java/com/backend/domain/shipfishingpost/dto/response/ShipFishingPostResponse.java
  backend/src/main/java/com/backend/domain/shipfishingpost/repository/ShipFishingPostQueryRepository.java
  backend/src/main/java/com/backend/domain/shipfishingpost/repository/ShipFishingPostRepository.java
  backend/src/main/java/com/backend/domain/shipfishingpost/repository/ShipFishingPostRepositoryImpl.java
  backend/src/main/java/com/backend/domain/shipfishingpost/service/ShipFishingPostService.java
  backend/src/main/java/com/backend/domain/shipfishingpost/service/ShipFishingPostServiceImpl.java
  backend/src/main/java/com/backend/domain/shipfishingpostfish/entity/ShipFishingPostFish.java
  backend/src/main/java/com/backend/domain/shipfishingpostfish/entity/ShipFishingPostFishId.java
  backend/src/main/java/com/backend/domain/shipfishingpostfish/repository/ShipFishingPostFishJpaRepository.java
  backend/src/main/java/com/backend/domain/shipfishingpostfish/repository/ShipFishingPostFishRepository.java
  backend/src/main/java/com/backend/domain/shipfishingpostfish/repository/ShipFishingPostFishRepositoryImpl.java
  backend/src/main/java/com/backend/global/advice/GlobalControllerAdvice.java
  backend/src/main/java/com/backend/global/config/QuerydslConfig.java
  backend/src/main/java/com/backend/global/dto/response/ScrollResponse.java
  backend/src/main/java/com/backend/global/exception/GlobalErrorCode.java
  backend/src/test/java/com/backend/domain/fish/repository/FishRepositoryTest.java
  backend/src/test/java/com/backend/domain/ship/repository/ShipRepositoryTest.java
  backend/src/test/java/com/backend/domain/shipfishingpostfish/repository/ShipFishingPostFishRepositoryTest.java
  backend/src/test/java/com/backend/domain/shipfishposts/repository/ShipFishingPostRepositoryTest.java
  backend/src/test/java/com/backend/domain/shipfishposts/service/ShipFishingPostServiceTest.java
Labels: enhancement

#24 MIKKI-89
  backend/src/main/java/com/backend/domain/review/controller/ReviewController.java
  backend/src/main/java/com/backend/domain/review/exception/ReviewErrorCode.java
  backend/src/main/java/com/backend/domain/review/repository/ReviewRepository.java
  backend/src/main/java/com/backend/domain/review/repository/ReviewRepositoryImpl.java
  backend/src/main/java/com/backend/domain/review/service/ReviewService.java
  backend/src/main/java/com/backend/domain/review/service/ReviewServiceImpl.java
  backend/src/test/java/com/backend/domain/review/controller/ReviewControllerTest.java
  backend/src/test/java/com/backend/domain/review/repository/ReviewRepositoryTest.java
  backend/src/test/java/com/backend/domain/review/service/ReviewServiceTest.java
Labels: enhancement

#26 MIKKI-82
  backend/src/main/java/com/backend/domain/captain/dto/Response/CaptainResponse.java
  backend/src/main/java/com/backend/domain/captain/exception/CaptainErrorCode.java
  backend/src/main/java/com/backend/domain/captain/repository/CaptainQueryRepository.java
  backend/src/main/java/com/backend/domain/captain/service/CaptainServiceImpl.java
  backend/src/test/java/com/backend/domain/captain/controller/CaptainControllerTest.java
  backend/src/test/java/com/backend/domain/captain/service/CaptainServiceTest.java
Labels: refactor

#27 MIKKI-99
  backend/src/main/java/com/backend/domain/captain/exception/CaptainErrorCode.java
  backend/src/main/java/com/backend/domain/captain/exception/CaptainException.java
  backend/src/main/java/com/backend/domain/fish/exception/FishErrorCode.java
  backend/src/main/java/com/backend/domain/fish/exception/FishException.java
  backend/src/main/java/com/backend/domain/fishencyclopedia/controller/FishEncyclopediaController.java
  backend/src/main/java/com/backend/domain/fishencyclopedia/exception/FishEncyclopediaErrorCode.java
  backend/src/main/java/com/backend/domain/fishencyclopedia/exception/FishEncyclopediaException.java
  backend/src/main/java/com/backend/domain/fishencyclopedia/repository/FishEncyclopediaQueryRepository.java
  backend/src/main/java/com/backend/domain/fishencyclopedia/repository/FishEncyclopediaRepository.java
  backend/src/main/java/com/backend/domain/fishencyclopedia/repository/FishEncyclopediaRepositoryImpl.java
  backend/src/main/java/com/backend/domain/fishencyclopedia/service/FishEncyclopediaService.java
  backend/src/main/java/com/backend/domain/fishencyclopedia/service/FishEncyclopediaServiceImpl.java
  backend/src/main/java/com/backend/domain/member/exception/MemberErrorCode.java
  backend/src/main/java/com/backend/domain/member/exception/MemberException.java
  backend/src/main/java/com/backend/domain/reservation/exception/ReservationErrorCode.java
  backend/src/main/java/com/backend/domain/reservation/exception/ReservationException.java
  backend/src/main/java/com/backend/domain/review/exception/ReviewErrorCode.java
  backend/src/main/java/com/backend/domain/review/exception/ReviewException.java
  backend/src/main/java/com/backend/domain/ship/exception/ShipErrorCode.java
  backend/src/main/java/com/backend/domain/ship/exception/ShipException.java
  backend/src/main/java/com/backend/domain/shipfishingpost/exception/ShipFishingPostErrorCode.java
  backend/src/main/java/com/backend/domain/shipfishingpost/exception/ShipFishingPostException.java
  backend/src/main/java/com/backend/global/advice/GlobalControllerAdvice.java
  backend/src/main/java/com/backend/global/auth/exception/JwtAuthenticationErrorCode.java
  backend/src/main/java/com/backend/global/auth/exception/JwtAuthenticationException.java
  backend/src/main/java/com/backend/global/auth/jwt/JwtTokenProvider.java
  backend/src/main/java/com/backend/global/auth/oauth2/service/CustomOAuth2UserService.java
  backend/src/main/java/com/backend/global/dto/response/ScrollResponse.java
  backend/src/main/java/com/backend/global/exception/ErrorCode.java
  backend/src/main/java/com/backend/global/exception/GlobalErrorCode.java
  backend/src/main/java/com/backend/global/exception/GlobalException.java
  backend/src/main/java/com/backend/global/storage/exception/StorageErrorCode.java
  backend/src/main/java/com/backend/global/storage/exception/StorageException.java
  backend/src/test/java/com/backend/domain/captain/service/CaptainServiceTest.java
  backend/src/test/java/com/backend/domain/fishencyclopedia/controller/FishEncyclopediaControllerTest.java
  backend/src/test/java/com/backend/domain/fishencyclopedia/repository/FishEncyclopediaRepositoryTest.java
  backend/src/test/java/com/backend/domain/fishencyclopedia/service/FishEncyclopediaServiceTest.java
  backend/src/test/java/com/backend/domain/shipfishposts/repository/ShipFishingPostRepositoryTest.java
  backend/src/test/java/com/backend/domain/shipfishposts/service/ShipFishingPostServiceTest.java
Labels: enhancement

#29 MIKKI-100
  backend/src/main/java/com/backend/domain/member/converter/MemberConverter.java
  backend/src/main/java/com/backend/domain/member/dto/MemberResponse.java
  backend/src/main/java/com/backend/domain/member/repository/MemberQueryRepository.java
  backend/src/main/java/com/backend/domain/member/repository/MemberRepository.java
  backend/src/main/java/com/backend/domain/member/repository/MemberRepositoryImpl.java
  backend/src/main/java/com/backend/domain/member/service/MemberService.java
  backend/src/main/java/com/backend/domain/member/service/MemberServiceImpl.java
  backend/src/test/java/com/backend/domain/member/service/MemberServiceTest.java
Labels: enhancement, refactor

#28 MIKKI-101
  backend/src/main/java/com/backend/domain/auth/controller/AuthController.java
  backend/src/main/java/com/backend/domain/captain/dto/Request/CaptainRequest.java
  backend/src/main/java/com/backend/domain/captain/service/CaptainService.java
  backend/src/main/java/com/backend/domain/captain/service/CaptainServiceImpl.java
  backend/src/test/java/com/backend/domain/captain/controller/CaptainControllerTest.java
  backend/src/test/java/com/backend/domain/captain/repository/CaptainRepositoryTest.java
  backend/src/test/java/com/backend/domain/captain/service/CaptainServiceTest.java
Labels: enhancement, refactor

#30 MIKKI-99
  backend/build.gradle
  backend/src/main/java/com/backend/domain/captain/entity/Captain.java
  backend/src/main/java/com/backend/domain/catchmaxlength/converter/CatchMaxLengthConvert.java
  backend/src/main/java/com/backend/domain/catchmaxlength/entity/CatchMaxLength.java
  backend/src/main/java/com/backend/domain/fish/entity/Fish.java
  backend/src/main/java/com/backend/domain/fishencyclopedia/controller/FishEncyclopediaController.java
  backend/src/main/java/com/backend/domain/fishencyclopedia/dto/response/FishEncyclopediaResponse.java
  backend/src/main/java/com/backend/domain/fishencyclopedia/entity/FishEncyclopedia.java
  backend/src/main/java/com/backend/domain/fishencyclopedia/repository/FishEncyclopediaQueryRepository.java
  backend/src/main/java/com/backend/domain/fishencyclopedia/repository/FishEncyclopediaRepository.java
  backend/src/main/java/com/backend/domain/fishencyclopedia/repository/FishEncyclopediaRepositoryImpl.java
  backend/src/main/java/com/backend/domain/fishencyclopedia/service/FishEncyclopediaService.java
  backend/src/main/java/com/backend/domain/fishencyclopedia/service/FishEncyclopediaServiceImpl.java
  backend/src/main/java/com/backend/domain/fishingtripposts/entity/FishingTripPosts.java
  backend/src/main/java/com/backend/domain/fishpoint/entity/FishPoint.java
  backend/src/main/java/com/backend/domain/likes/entity/Likes.java
  backend/src/main/java/com/backend/domain/member/entity/Member.java
  backend/src/main/java/com/backend/domain/reservation/entity/Reservation.java
  backend/src/main/java/com/backend/domain/reservationdate/entity/ReservationDate.java
  backend/src/main/java/com/backend/domain/review/controller/ReviewController.java
  backend/src/main/java/com/backend/domain/review/entity/Review.java
  backend/src/main/java/com/backend/domain/ship/entity/Ship.java
  backend/src/main/java/com/backend/domain/shipfishingpost/controller/ShipFishingPostController.java
  backend/src/main/java/com/backend/domain/shipfishingpost/entity/ShipFishingPost.java
  backend/src/main/java/com/backend/domain/shipfishingpostfish/entity/ShipFishingPostFish.java
  backend/src/main/java/com/backend/global/dto/request/GlobalRequest.java
  backend/src/main/java/com/backend/global/dto/response/ScrollResponse.java
  backend/src/main/java/com/backend/global/exception/GlobalErrorCode.java
  backend/src/main/java/com/backend/global/util/QuerydslUtil.java
  backend/src/test/java/com/backend/domain/fishencyclopedia/controller/FishEncyclopediaControllerTest.java
  backend/src/test/java/com/backend/domain/fishencyclopedia/repository/FishEncyclopediaRepositoryTest.java
  backend/src/test/java/com/backend/domain/fishencyclopedia/service/FishEncyclopediaServiceTest.java
  backend/src/test/java/com/backend/domain/shipfishposts/service/ShipFishingPostServiceTest.java
Labels: enhancement, refactor

#31 MIKKI-61
  backend/src/main/java/com/backend/global/config/S3Config.java
  backend/src/main/java/com/backend/global/config/SchedulingConfig.java
  backend/src/main/java/com/backend/global/storage/StorageProperties.java
  backend/src/main/java/com/backend/global/storage/controller/StorageController.java
  backend/src/main/java/com/backend/global/storage/converter/StorageConverter.java
  backend/src/main/java/com/backend/global/storage/dto/request/FileUploadRequest.java
  backend/src/main/java/com/backend/global/storage/dto/response/FileUploadResponse.java
  backend/src/main/java/com/backend/global/storage/entity/File.java
  backend/src/main/java/com/backend/global/storage/exception/StorageErrorCode.java
  backend/src/main/java/com/backend/global/storage/repository/StorageJpaRepository.java
  backend/src/main/java/com/backend/global/storage/repository/StorageQueryRepository.java
  backend/src/main/java/com/backend/global/storage/repository/StorageRepository.java
  backend/src/main/java/com/backend/global/storage/repository/StorageRepositoryImpl.java
  backend/src/main/java/com/backend/global/storage/scheduler/FileCleanupScheduler.java
  backend/src/main/java/com/backend/global/storage/service/S3StorageService.java
  backend/src/main/java/com/backend/global/storage/service/StorageCleanupService.java
  backend/src/main/java/com/backend/global/storage/service/StorageCleanupServiceImpl.java
  backend/src/main/java/com/backend/global/storage/service/StorageService.java
  backend/src/main/java/com/backend/global/storage/service/dto/FileToUpload.java
Labels: enhancement, refactor

#34 MIKKI-45
  backend/src/main/java/com/backend/domain/captain/converter/CaptainConverter.java
  backend/src/main/java/com/backend/domain/captain/dto/Request/CaptainRequest.java
  backend/src/main/java/com/backend/domain/captain/service/CaptainServiceImpl.java
  backend/src/main/java/com/backend/domain/fishingtrippost/controller/FishingTripPostController.java
  backend/src/main/java/com/backend/domain/fishingtrippost/converter/FishingTripPostConvert.java
  backend/src/main/java/com/backend/domain/fishingtrippost/dto/request/FishingTripPostRequest.java
  backend/src/main/java/com/backend/domain/fishingtrippost/entity/FishingTripPost.java
  backend/src/main/java/com/backend/domain/fishingtrippost/exception/FishingTripPostErrorCode.java
  backend/src/main/java/com/backend/domain/fishingtrippost/exception/FishingTripPostException.java
  backend/src/main/java/com/backend/domain/fishingtrippost/repository/FishingTripPostJpaRepository.java
  backend/src/main/java/com/backend/domain/fishingtrippost/repository/FishingTripPostQueryRepository.java
  backend/src/main/java/com/backend/domain/fishingtrippost/repository/FishingTripPostRepository.java
  backend/src/main/java/com/backend/domain/fishingtrippost/repository/FishingTripPostRepositoryImpl.java
  backend/src/main/java/com/backend/domain/fishingtrippost/service/FishingTripPostService.java
  backend/src/main/java/com/backend/domain/fishingtrippost/service/FishingTripPostServiceImpl.java
  backend/src/main/java/com/backend/domain/fishpoint/exception/FishPointErrorCode.java
  backend/src/main/java/com/backend/domain/fishpoint/exception/FishPointException.java
  backend/src/main/java/com/backend/domain/member/dto/MemberRequest.java
  backend/src/main/java/com/backend/domain/member/entity/Member.java
  backend/src/main/java/com/backend/domain/member/repository/MemberRepository.java
  backend/src/main/java/com/backend/domain/member/repository/MemberRepositoryImpl.java
  backend/src/test/java/com/backend/domain/captain/controller/CaptainControllerTest.java
  backend/src/test/java/com/backend/domain/captain/repository/CaptainRepositoryTest.java
  backend/src/test/java/com/backend/domain/captain/service/CaptainServiceTest.java
  backend/src/test/java/com/backend/domain/fishingtrippost/controller/FishingTripPostControllerTest.java
  backend/src/test/java/com/backend/domain/fishingtrippost/repository/FishingTripPostRepositoryTest.java
  backend/src/test/java/com/backend/domain/fishingtrippost/service/FishingTripPostServiceTest.java
Labels: enhancement

#33 MIKKI-99
  backend/src/main/java/com/backend/domain/catchmaxlength/entity/CatchMaxLength.java
  backend/src/main/java/com/backend/domain/fish/entity/Fish.java
  backend/src/main/java/com/backend/domain/fishencyclopedia/controller/FishEncyclopediaController.java
  backend/src/main/java/com/backend/domain/fishencyclopedia/dto/response/FishEncyclopediaResponse.java
  backend/src/main/java/com/backend/domain/fishencyclopedia/entity/FishEncyclopedia.java
  backend/src/main/java/com/backend/domain/fishencyclopedia/repository/FishEncyclopediaQueryRepository.java
  backend/src/main/java/com/backend/domain/fishencyclopedia/repository/FishEncyclopediaRepository.java
  backend/src/main/java/com/backend/domain/fishencyclopedia/repository/FishEncyclopediaRepositoryImpl.java
  backend/src/main/java/com/backend/domain/fishencyclopedia/service/FishEncyclopediaService.java
  backend/src/main/java/com/backend/domain/fishencyclopedia/service/FishEncyclopediaServiceImpl.java
  backend/src/test/java/com/backend/domain/fishencyclopedia/controller/FishEncyclopediaControllerTest.java
  backend/src/test/java/com/backend/domain/fishencyclopedia/repository/FishEncyclopediaRepositoryTest.java
  backend/src/test/java/com/backend/domain/fishencyclopedia/service/FishEncyclopediaServiceTest.java
  backend/src/test/java/com/backend/global/util/BaseTest.java
Labels: enhancement, refactor

#36 MIKKI-96
  backend/src/main/java/com/backend/domain/member/dto/MemberResponse.java
  backend/src/main/java/com/backend/domain/reservation/controller/ReservationController.java
  backend/src/main/java/com/backend/domain/reservation/converter/ReservationConverter.java
  backend/src/main/java/com/backend/domain/reservation/dto/request/ReservationRequest.java
  backend/src/main/java/com/backend/domain/reservation/dto/response/ReservationResponse.java
  backend/src/main/java/com/backend/domain/reservation/entity/Reservation.java
  backend/src/main/java/com/backend/domain/reservation/entity/ReservationStatus.java
  backend/src/main/java/com/backend/domain/reservation/exception/ReservationErrorCode.java
  backend/src/main/java/com/backend/domain/reservation/repository/ReservationRepository.java
  backend/src/main/java/com/backend/domain/reservation/repository/ReservationRepositoryImpl.java
  backend/src/main/java/com/backend/domain/reservation/service/ReservationService.java
  backend/src/main/java/com/backend/domain/reservation/service/ReservationServiceImpl.java
  backend/src/main/java/com/backend/domain/reservation/util/ReservationUtil.java
  backend/src/main/java/com/backend/domain/reservationdate/Controller/ReservationDateController.java
  backend/src/main/java/com/backend/domain/reservationdate/converter/ReservationDateConverter.java
  backend/src/main/java/com/backend/domain/reservationdate/dto/response/ReservationDateResponse.java
  backend/src/main/java/com/backend/domain/reservationdate/entity/ReservationDate.java
  backend/src/main/java/com/backend/domain/reservationdate/entity/ReservationDateId.java
  backend/src/main/java/com/backend/domain/reservationdate/repository/ReservationDateJpaRepository.java
  backend/src/main/java/com/backend/domain/reservationdate/repository/ReservationDateQueryRepository.java
  backend/src/main/java/com/backend/domain/reservationdate/repository/ReservationDateRepository.java
  backend/src/main/java/com/backend/domain/reservationdate/repository/ReservationDateRepositoryImpl.java
  backend/src/main/java/com/backend/domain/reservationdate/service/ReservationDateService.java
  backend/src/main/java/com/backend/domain/reservationdate/service/ReservationDateServiceImpl.java
  backend/src/main/java/com/backend/domain/shipfishingpost/controller/ShipFishingPostController.java
  backend/src/main/java/com/backend/domain/shipfishingpost/converter/ShipFishingPostConverter.java
  backend/src/main/java/com/backend/domain/shipfishingpost/dto/request/ShipFishingPostRequest.java
  backend/src/main/java/com/backend/domain/shipfishingpost/dto/response/ShipFishingPostResponse.java
  backend/src/main/java/com/backend/domain/shipfishingpost/entity/ShipFishingPost.java
  backend/src/main/java/com/backend/domain/shipfishingpost/repository/ShipFishingPostQueryRepository.java
  backend/src/main/java/com/backend/domain/shipfishingpost/repository/ShipFishingPostRepository.java
  backend/src/main/java/com/backend/domain/shipfishingpost/repository/ShipFishingPostRepositoryImpl.java
  backend/src/main/java/com/backend/domain/shipfishingpost/service/ShipFishingPostServiceImpl.java
  backend/src/main/java/com/backend/domain/shipfishingpostfish/converter/ShipFishingPostFishConverter.java
  backend/src/main/java/com/backend/domain/shipfishingpostfish/repository/ShipFishingPostFishQueryRepository.java
  backend/src/main/java/com/backend/domain/shipfishingpostfish/repository/ShipFishingPostFishRepository.java
  backend/src/main/java/com/backend/domain/shipfishingpostfish/repository/ShipFishingPostFishRepositoryImpl.java
  backend/src/main/java/com/backend/global/advice/GlobalControllerAdvice.java
  backend/src/main/java/com/backend/global/exception/GlobalErrorCode.java
  backend/src/test/java/com/backend/domain/reservation/repository/ReservationRepositoryTest.java
  backend/src/test/java/com/backend/domain/reservation/service/ReservationConcurrencyTest.java
  backend/src/test/java/com/backend/domain/reservationdate/repository/ReservationDateRepositoryTest.java
  backend/src/test/java/com/backend/domain/reservationdate/service/ReservationDateServiceTest.java
  backend/src/test/java/com/backend/domain/shipfishingpostfish/repository/ShipFishingPostFishRepositoryTest.java
  backend/src/test/java/com/backend/domain/shipfishposts/repository/ShipFishingPostRepositoryTest.java
  backend/src/test/java/com/backend/domain/shipfishposts/service/ShipFishingPostServiceTest.java
Labels: enhancement

#37 MIKKI-109
  backend/src/main/java/com/backend/domain/captain/controller/CaptainController.java
  backend/src/main/java/com/backend/domain/fishingtrippost/controller/FishingTripPostController.java
  backend/src/main/java/com/backend/domain/fishingtrippost/converter/FishingTripPostConvert.java
  backend/src/main/java/com/backend/domain/fishingtrippost/dto/request/FishingTripPostRequest.java
  backend/src/main/java/com/backend/domain/fishingtrippost/entity/FishingTripPost.java
  backend/src/main/java/com/backend/domain/fishingtrippost/exception/FishingTripPostErrorCode.java
  backend/src/main/java/com/backend/domain/fishingtrippost/repository/FishingTripPostRepository.java
  backend/src/main/java/com/backend/domain/fishingtrippost/repository/FishingTripPostRepositoryImpl.java
  backend/src/main/java/com/backend/domain/fishingtrippost/service/FishingTripPostService.java
  backend/src/main/java/com/backend/domain/fishingtrippost/service/FishingTripPostServiceImpl.java
  backend/src/test/java/com/backend/domain/captain/controller/CaptainControllerTest.java
  backend/src/test/java/com/backend/domain/fishingtrippost/controller/FishingTripPostControllerTest.java
  backend/src/test/java/com/backend/domain/fishingtrippost/repository/FishingTripPostRepositoryTest.java
  backend/src/test/java/com/backend/domain/fishingtrippost/service/FishingTripPostServiceTest.java
Labels: enhancement

#38 MIKKI-111
  backend/src/main/java/com/backend/domain/reservation/controller/ReservationController.java
  backend/src/main/java/com/backend/domain/reservation/dto/request/ReservationRequest.java
  backend/src/main/java/com/backend/domain/reservation/dto/response/ReservationResponse.java
  backend/src/main/java/com/backend/domain/reservation/exception/ReservationErrorCode.java
  backend/src/main/java/com/backend/domain/reservation/repository/ReservationQueryRepository.java
  backend/src/main/java/com/backend/domain/reservation/repository/ReservationRepository.java
  backend/src/main/java/com/backend/domain/reservation/repository/ReservationRepositoryImpl.java
  backend/src/main/java/com/backend/domain/reservation/service/ReservationService.java
  backend/src/main/java/com/backend/domain/reservation/service/ReservationServiceImpl.java
  backend/src/main/java/com/backend/domain/reservationdate/Controller/ReservationDateController.java
  backend/src/main/java/com/backend/domain/shipfishingpost/controller/ShipFishingPostController.java
  backend/src/main/java/com/backend/domain/shipfishingpost/dto/request/ShipFishingPostRequest.java
  backend/src/test/java/com/backend/domain/reservation/repository/ReservationRepositoryTest.java
  backend/src/test/java/com/backend/domain/reservation/service/ReservationServiceTest.java
Labels: enhancement

#39 MIKKI-110
  backend/src/main/java/com/backend/domain/fishingtrippost/controller/FishingTripPostController.java
  backend/src/main/java/com/backend/domain/fishingtrippost/dto/response/FishingTripPostResponse.java
  backend/src/main/java/com/backend/domain/fishingtrippost/entity/FishingTripPost.java
  backend/src/main/java/com/backend/domain/fishingtrippost/repository/FishingTripPostQueryRepository.java
  backend/src/main/java/com/backend/domain/fishingtrippost/repository/FishingTripPostRepository.java
  backend/src/main/java/com/backend/domain/fishingtrippost/repository/FishingTripPostRepositoryImpl.java
  backend/src/main/java/com/backend/domain/fishingtrippost/service/FishingTripPostService.java
  backend/src/main/java/com/backend/domain/fishingtrippost/service/FishingTripPostServiceImpl.java
  backend/src/test/java/com/backend/domain/fishingtrippost/controller/FishingTripPostControllerTest.java
  backend/src/test/java/com/backend/domain/fishingtrippost/repository/FishingTripPostRepositoryTest.java
  backend/src/test/java/com/backend/domain/fishingtrippost/service/FishingTripPostServiceTest.java
Labels: enhancement

#40 MIKKI-107
  backend/src/main/java/com/backend/domain/fish/controller/FishController.java
  backend/src/main/java/com/backend/domain/fish/domain/SpawnLocation.java
  backend/src/main/java/com/backend/domain/fish/dto/FishResponse.java
  backend/src/main/java/com/backend/domain/fish/entity/Fish.java
  backend/src/main/java/com/backend/domain/fish/exception/FishErrorCode.java
  backend/src/main/java/com/backend/domain/fish/repository/FishQueryRepository.java
  backend/src/main/java/com/backend/domain/fish/repository/FishRepository.java
  backend/src/main/java/com/backend/domain/fish/repository/FishRepositoryImpl.java
  backend/src/main/java/com/backend/domain/fish/service/FishService.java
  backend/src/main/java/com/backend/domain/fish/service/FishServiceImpl.java
  backend/src/main/java/com/backend/domain/fishencyclopedia/dto/response/FishEncyclopediaResponse.java
  backend/src/main/java/com/backend/domain/fishencyclopedia/exception/FishEncyclopediaErrorCode.java
  backend/src/main/java/com/backend/domain/fishencyclopedia/service/FishEncyclopediaServiceImpl.java
  backend/src/main/java/com/backend/domain/fishpoint/exception/FishPointErrorCode.java
  backend/src/main/java/com/backend/global/config/SecurityConfig.java
  backend/src/test/java/com/backend/domain/fish/controller/FishControllerTest.java
  backend/src/test/java/com/backend/domain/fish/repository/FishRepositoryTest.java
  backend/src/test/java/com/backend/domain/fish/service/FishServiceTest.java
  backend/src/test/java/com/backend/domain/fishencyclopedia/service/FishEncyclopediaServiceTest.java
  backend/src/test/java/com/backend/global/config/TestSecurityConfig.java
Labels: enhancement

#42 MIKKI-120
  backend/src/main/java/com/backend/domain/fishingtrippost/converter/FishingTripPostConverter.java
  backend/src/main/java/com/backend/domain/fishingtrippost/repository/FishingTripPostRepository.java
  backend/src/main/java/com/backend/domain/fishingtrippost/repository/FishingTripPostRepositoryImpl.java
  backend/src/main/java/com/backend/domain/fishingtrippost/service/FishingTripPostServiceImpl.java
  backend/src/main/java/com/backend/domain/fishingtriprecruitment/controller/FishingTripRecruitmentController.java
  backend/src/main/java/com/backend/domain/fishingtriprecruitment/converter/FishingTripRecruitmentConverter.java
  backend/src/main/java/com/backend/domain/fishingtriprecruitment/domain/FishingLevel.java
  backend/src/main/java/com/backend/domain/fishingtriprecruitment/domain/RecruitmentStatus.java
  backend/src/main/java/com/backend/domain/fishingtriprecruitment/dto/request/FishingTripRecruitmentRequest.java
  backend/src/main/java/com/backend/domain/fishingtriprecruitment/entity/FishingTripRecruitment.java
  backend/src/main/java/com/backend/domain/fishingtriprecruitment/exception/FishingTripRecruitmentErrorCode.java
  backend/src/main/java/com/backend/domain/fishingtriprecruitment/exception/FishingTripRecruitmentException.java
  backend/src/main/java/com/backend/domain/fishingtriprecruitment/repository/FishingTripRecruitmentJpaRepository.java
  backend/src/main/java/com/backend/domain/fishingtriprecruitment/repository/FishingTripRecruitmentQueryRepository.java
  backend/src/main/java/com/backend/domain/fishingtriprecruitment/repository/FishingTripRecruitmentRepository.java
  backend/src/main/java/com/backend/domain/fishingtriprecruitment/repository/FishingTripRecruitmentRepositoryImpl.java
  backend/src/main/java/com/backend/domain/fishingtriprecruitment/service/FishingTripRecruitmentService.java
  backend/src/main/java/com/backend/domain/fishingtriprecruitment/service/FishingTripRecruitmentServiceImpl.java
  backend/src/main/java/com/backend/global/validator/EnumValidatorForEnum.java
  backend/src/main/java/com/backend/global/validator/EnumValidatorForString.java
  backend/src/main/java/com/backend/global/validator/ValidEnum.java
  backend/src/test/java/com/backend/domain/fishingtrippost/repository/FishingTripPostRepositoryTest.java
  backend/src/test/java/com/backend/domain/fishingtriprecruitment/controller/FishingTripRecruitmentControllerTest.java
  backend/src/test/java/com/backend/domain/fishingtriprecruitment/repository/FishingTripRecruitmentRepositoryTest.java
  backend/src/test/java/com/backend/domain/fishingtriprecruitment/service/FishingTripRecruitmentServiceTest.java
Labels: enhancement

#41 MIKKI-123
  backend/src/main/java/com/backend/domain/fish/entity/Fish.java
  backend/src/main/java/com/backend/domain/fish/repository/FishQueryRepository.java
  backend/src/main/java/com/backend/domain/fish/repository/FishRepository.java
  backend/src/main/java/com/backend/domain/fish/repository/FishRepositoryImpl.java
  backend/src/main/java/com/backend/domain/fish/scheduler/FishScheduler.java
  backend/src/main/java/com/backend/domain/fishencyclopedia/entity/FishEncyclopedia.java
  backend/src/main/java/com/backend/domain/fishencyclopedia/repository/FishEncyclopediaQueryRepository.java
  backend/src/main/java/com/backend/domain/fishencyclopedia/repository/FishEncyclopediaRepository.java
  backend/src/main/java/com/backend/domain/fishencyclopedia/repository/FishEncyclopediaRepositoryImpl.java
  backend/src/test/java/com/backend/domain/fish/repository/FishRepositoryTest.java
  backend/src/test/java/com/backend/domain/fishencyclopedia/repository/FishEncyclopediaRepositoryTest.java
Labels: enhancement

#43 MIKKI-122
  backend/src/main/java/com/backend/domain/fish/controller/FishController.java
  backend/src/main/java/com/backend/domain/fish/dto/FishRequest.java
  backend/src/main/java/com/backend/domain/fish/dto/FishResponse.java
  backend/src/main/java/com/backend/domain/fish/entity/Fish.java
  backend/src/main/java/com/backend/domain/fish/repository/FishQueryRepository.java
  backend/src/main/java/com/backend/domain/fish/repository/FishRepository.java
  backend/src/main/java/com/backend/domain/fish/repository/FishRepositoryImpl.java
  backend/src/main/java/com/backend/domain/fish/service/FishService.java
  backend/src/main/java/com/backend/domain/fish/service/FishServiceImpl.java
  backend/src/main/java/com/backend/domain/fishencyclopedia/repository/FishEncyclopediaQueryRepository.java
  backend/src/main/java/com/backend/global/config/SecurityConfig.java
  backend/src/test/java/com/backend/domain/fish/controller/FishControllerTest.java
  backend/src/test/java/com/backend/domain/fish/repository/FishRepositoryTest.java
  backend/src/test/java/com/backend/domain/fish/service/FishServiceTest.java
Labels: enhancement

#44 MIKKI-129
  backend/src/main/java/com/backend/domain/fishingtriprecruitment/controller/FishingTripRecruitmentController.java
  backend/src/main/java/com/backend/domain/fishingtriprecruitment/entity/FishingTripRecruitment.java
  backend/src/main/java/com/backend/domain/fishingtriprecruitment/service/FishingTripRecruitmentService.java
  backend/src/main/java/com/backend/domain/fishingtriprecruitment/service/FishingTripRecruitmentServiceImpl.java
  backend/src/test/java/com/backend/domain/fishingtriprecruitment/controller/FishingTripRecruitmentControllerTest.java
  backend/src/test/java/com/backend/domain/fishingtriprecruitment/service/FishingTripRecruitmentServiceTest.java
Labels: enhancement

#45 MIKKI-83
  backend/src/main/java/com/backend/domain/captain/dto/Request/CaptainRequest.java
  backend/src/main/java/com/backend/domain/captain/repository/CaptainQueryRepository.java
  backend/src/main/java/com/backend/domain/captain/service/CaptainServiceImpl.java
  backend/src/main/java/com/backend/domain/member/dto/MemberRequest.java
  backend/src/main/java/com/backend/domain/member/dto/MemberResponse.java
  backend/src/main/java/com/backend/domain/member/entity/Member.java
  backend/src/main/java/com/backend/domain/member/repository/MemberQueryRepository.java
  backend/src/main/java/com/backend/domain/member/service/MemberServiceImpl.java
  backend/src/main/java/com/backend/domain/review/controller/ReviewController.java
  backend/src/main/java/com/backend/domain/review/converter/ReviewConverter.java
  backend/src/main/java/com/backend/domain/review/dto/request/ReviewRequest.java
  backend/src/main/java/com/backend/domain/review/dto/response/ReviewWithMemberResponse.java
  backend/src/main/java/com/backend/domain/review/entity/Review.java
  backend/src/main/java/com/backend/domain/review/repository/ReviewJpaRepository.java
  backend/src/main/java/com/backend/domain/review/repository/ReviewQueryRepository.java
  backend/src/main/java/com/backend/domain/review/repository/ReviewRepository.java
  backend/src/main/java/com/backend/domain/review/repository/ReviewRepositoryImpl.java
  backend/src/main/java/com/backend/domain/review/service/ReviewService.java
  backend/src/main/java/com/backend/domain/review/service/ReviewServiceImpl.java
  backend/src/main/java/com/backend/global/auth/oauth2/handler/OAuth2AuthenticationSuccessHandler.java
  backend/src/main/java/com/backend/global/auth/oauth2/service/CustomOAuth2UserService.java
  backend/src/test/java/com/backend/domain/captain/service/CaptainServiceTest.java
  backend/src/test/java/com/backend/domain/member/controller/MemberControllerTest.java
  backend/src/test/java/com/backend/domain/member/service/MemberServiceTest.java
  backend/src/test/java/com/backend/domain/review/controller/ReviewControllerTest.java
  backend/src/test/java/com/backend/domain/review/repository/ReviewRepositoryTest.java
  backend/src/test/java/com/backend/domain/review/service/ReviewServiceTest.java
Labels: refactor

#46 MIKKI-113
  backend/src/main/java/com/backend/domain/reservation/controller/ReservationController.java
  backend/src/main/java/com/backend/domain/reservation/dto/response/ReservationResponse.java
  backend/src/main/java/com/backend/domain/reservation/entity/Reservation.java
  backend/src/main/java/com/backend/domain/reservation/repository/ReservationQueryRepository.java
  backend/src/main/java/com/backend/domain/reservation/repository/ReservationRepository.java
  backend/src/main/java/com/backend/domain/reservation/repository/ReservationRepositoryImpl.java
  backend/src/main/java/com/backend/domain/reservation/service/ReservationService.java
  backend/src/main/java/com/backend/domain/reservation/service/ReservationServiceImpl.java
  backend/src/main/java/com/backend/domain/reservationdate/controller/ReservationDateController.java
  backend/src/main/java/com/backend/domain/reservationdate/repository/ReservationDateJpaRepository.java
  backend/src/main/java/com/backend/domain/reservationdate/repository/ReservationDateRepository.java
  backend/src/main/java/com/backend/domain/reservationdate/repository/ReservationDateRepositoryImpl.java
  backend/src/main/java/com/backend/global/util/QuerydslUtil.java
  backend/src/test/java/com/backend/domain/reservation/repository/ReservationRepositoryTest.java
  backend/src/test/java/com/backend/domain/reservation/service/ReservationConcurrencyTest.java
  backend/src/test/java/com/backend/domain/reservation/service/ReservationServiceTest.java
Labels: enhancement

#48 MIKKI-127
  backend/src/main/java/com/backend/domain/fishingtriprecruitment/controller/FishingTripRecruitmentController.java
  backend/src/main/java/com/backend/domain/fishingtriprecruitment/domain/RecruitmentStatus.java
  backend/src/main/java/com/backend/domain/fishingtriprecruitment/dto/response/FishingTripRecruitmentResponse.java
  backend/src/main/java/com/backend/domain/fishingtriprecruitment/entity/FishingTripRecruitment.java
  backend/src/main/java/com/backend/domain/fishingtriprecruitment/repository/FishingTripRecruitmentQueryRepository.java
  backend/src/main/java/com/backend/domain/fishingtriprecruitment/repository/FishingTripRecruitmentRepository.java
  backend/src/main/java/com/backend/domain/fishingtriprecruitment/repository/FishingTripRecruitmentRepositoryImpl.java
  backend/src/main/java/com/backend/domain/fishingtriprecruitment/service/FishingTripRecruitmentService.java
  backend/src/main/java/com/backend/domain/fishingtriprecruitment/service/FishingTripRecruitmentServiceImpl.java
  backend/src/main/java/com/backend/domain/member/entity/Member.java
  backend/src/test/java/com/backend/domain/fishingtriprecruitment/controller/FishingTripRecruitmentControllerTest.java
  backend/src/test/java/com/backend/domain/fishingtriprecruitment/repository/FishingTripRecruitmentRepositoryTest.java
  backend/src/test/java/com/backend/domain/fishingtriprecruitment/service/FishingTripRecruitmentServiceTest.java
Labels: enhancement

#50 MIKKI-139
  backend/src/main/java/com/backend/domain/member/controller/MemberController.java
  backend/src/main/java/com/backend/domain/member/dto/MemberResponse.java
  backend/src/main/java/com/backend/domain/member/repository/MemberQueryRepository.java
  backend/src/main/java/com/backend/domain/member/service/MemberService.java
  backend/src/main/java/com/backend/domain/member/service/MemberServiceImpl.java
  backend/src/test/java/com/backend/domain/member/controller/MemberControllerTest.java
  backend/src/test/java/com/backend/domain/member/service/MemberServiceTest.java
Labels: enhancement

#52 MIKKI-144
  backend/src/main/java/com/backend/domain/fish/controller/FishController.java
  backend/src/main/java/com/backend/domain/fish/dto/FishResponse.java
  backend/src/main/java/com/backend/domain/fish/repository/FishQueryRepository.java
  backend/src/main/java/com/backend/domain/fish/repository/FishRepository.java
  backend/src/main/java/com/backend/domain/fish/repository/FishRepositoryImpl.java
  backend/src/main/java/com/backend/domain/fish/service/FishService.java
  backend/src/main/java/com/backend/domain/fish/service/FishServiceImpl.java
  backend/src/main/java/com/backend/domain/fishencyclopedia/controller/FishEncyclopediaController.java
  backend/src/main/java/com/backend/domain/ship/controller/ShipController.java
  backend/src/test/java/com/backend/domain/fish/controller/FishControllerTest.java
  backend/src/test/java/com/backend/domain/fish/repository/FishRepositoryTest.java
  backend/src/test/java/com/backend/domain/fish/service/FishServiceTest.java
Labels: enhancement

#54 MIKKI-138
  backend/src/main/java/com/backend/domain/ship/dto/response/ShipResponse.java
  backend/src/main/java/com/backend/domain/shipfishingpost/controller/ShipFishingPostController.java
  backend/src/main/java/com/backend/domain/shipfishingpost/converter/ShipFishingPostConverter.java
  backend/src/main/java/com/backend/domain/shipfishingpost/dto/request/ShipFishingPostRequest.java
  backend/src/main/java/com/backend/domain/shipfishingpost/dto/response/ShipFishingPostResponse.java
  backend/src/main/java/com/backend/domain/shipfishingpost/entity/ShipFishingPost.java
  backend/src/main/java/com/backend/domain/shipfishingpost/exception/ShipFishingPostErrorCode.java
  backend/src/main/java/com/backend/domain/shipfishingpost/repository/ShipFishingPostQueryRepository.java
  backend/src/main/java/com/backend/domain/shipfishingpost/repository/ShipFishingPostRepository.java
  backend/src/main/java/com/backend/domain/shipfishingpost/repository/ShipFishingPostRepositoryImpl.java
  backend/src/main/java/com/backend/domain/shipfishingpost/service/ShipFishingPostService.java
  backend/src/main/java/com/backend/domain/shipfishingpost/service/ShipFishingPostServiceImpl.java
  backend/src/main/java/com/backend/domain/shipfishingpostfish/converter/ShipFishingPostFishConverter.java
  backend/src/main/java/com/backend/domain/shipfishingpostfish/entity/ShipFishingPostFish.java
  backend/src/main/java/com/backend/domain/shipfishingpostfish/entity/ShipFishingPostFishId.java
  backend/src/main/java/com/backend/domain/shipfishingpostfish/repository/ShipFishingPostFishJpaRepository.java
  backend/src/main/java/com/backend/domain/shipfishingpostfish/repository/ShipFishingPostFishQueryRepository.java
  backend/src/main/java/com/backend/domain/shipfishingpostfish/repository/ShipFishingPostFishRepository.java
  backend/src/main/java/com/backend/domain/shipfishingpostfish/repository/ShipFishingPostFishRepositoryImpl.java
  backend/src/main/java/com/backend/global/util/QuerydslUtil.java
  backend/src/test/java/com/backend/domain/shipfishingpost/entity/ShipFishingPostTest.java
  backend/src/test/java/com/backend/domain/shipfishingpost/repository/ShipFishingPostRepositoryTest.java
  backend/src/test/java/com/backend/domain/shipfishingpost/service/ShipFishingPostServiceTest.java
  backend/src/test/java/com/backend/domain/shipfishingpostfish/repository/ShipFishingPostFishRepositoryTest.java
  backend/src/test/java/com/backend/domain/shipfishposts/repository/ShipFishingPostRepositoryTest.java
Labels: enhancement

#53 MIKKI-105
  backend/build.gradle
  backend/src/main/java/com/backend/domain/fishpoint/controller/FishPointController.java
  backend/src/main/java/com/backend/domain/fishpoint/converter/FishPointConverter.java
  backend/src/main/java/com/backend/domain/fishpoint/dto/request/FishPointRequest.java
  backend/src/main/java/com/backend/domain/fishpoint/dto/response/FishPointResponse.java
  backend/src/main/java/com/backend/domain/fishpoint/entity/FishPoint.java
  backend/src/main/java/com/backend/domain/fishpoint/repository/FishPointQueryRepository.java
  backend/src/main/java/com/backend/domain/fishpoint/repository/FishPointRepository.java
  backend/src/main/java/com/backend/domain/fishpoint/repository/FishPointRepositoryImpl.java
  backend/src/main/java/com/backend/domain/fishpoint/service/FishPointService.java
  backend/src/main/java/com/backend/domain/fishpoint/service/FishPointServiceImpl.java
  backend/src/main/java/com/backend/domain/region/entity/Region.java
  backend/src/main/java/com/backend/domain/region/entity/RegionType.java
  backend/src/test/java/com/backend/domain/fishencyclopedia/repository/FishEncyclopediaRepositoryTest.java
  backend/src/test/java/com/backend/domain/fishingtrippost/repository/FishingTripPostRepositoryTest.java
  backend/src/test/java/com/backend/domain/fishpoint/repository/FishPointRepositoryTest.java
  backend/src/test/java/com/backend/global/util/BaseTest.java
Labels: enhancement

#55 MIKKI-145
  .github/workflows/build-test.yml
  backend/build.gradle
  backend/src/main/java/com/backend/BackendApplication.java
  backend/src/main/java/com/backend/domain/fishingtrippost/controller/FishingTripPostController.java
  backend/src/main/java/com/backend/domain/fishingtrippost/notifier/FishingTripPostNotifier.java
  backend/src/main/java/com/backend/domain/fishingtrippost/service/FishingTripPostService.java
  backend/src/main/java/com/backend/domain/fishingtrippost/service/FishingTripPostServiceImpl.java
  backend/src/main/java/com/backend/domain/fishingtriprecruitment/repository/FishingTripRecruitmentQueryRepository.java
  backend/src/main/java/com/backend/domain/fishingtriprecruitment/repository/FishingTripRecruitmentRepository.java
  backend/src/main/java/com/backend/domain/fishingtriprecruitment/repository/FishingTripRecruitmentRepositoryImpl.java
  backend/src/main/java/com/backend/domain/fishingtriprecruitment/service/FishingTripRecruitmentService.java
  backend/src/main/java/com/backend/domain/fishingtriprecruitment/service/FishingTripRecruitmentServiceImpl.java
  backend/src/main/java/com/backend/domain/fishpoint/controller/FishPointController.java
  backend/src/main/java/com/backend/domain/fishpoint/converter/FishPointConverter.java
  backend/src/main/java/com/backend/domain/fishpoint/dto/request/FishPointRequest.java
  backend/src/main/java/com/backend/domain/fishpoint/dto/response/FishPointResponse.java
  backend/src/main/java/com/backend/domain/fishpoint/entity/FishPoint.java
  backend/src/main/java/com/backend/domain/fishpoint/repository/FishPointQueryRepository.java
  backend/src/main/java/com/backend/domain/fishpoint/repository/FishPointRepository.java
  backend/src/main/java/com/backend/domain/fishpoint/repository/FishPointRepositoryImpl.java
  backend/src/main/java/com/backend/domain/fishpoint/service/FishPointService.java
  backend/src/main/java/com/backend/domain/fishpoint/service/FishPointServiceImpl.java
  backend/src/main/java/com/backend/domain/member/repository/MemberQueryRepository.java
  backend/src/main/java/com/backend/domain/member/repository/MemberRepository.java
  backend/src/main/java/com/backend/domain/member/repository/MemberRepositoryImpl.java
  backend/src/main/java/com/backend/domain/region/entity/Region.java
  backend/src/main/java/com/backend/domain/region/entity/RegionType.java
  backend/src/main/java/com/backend/global/config/AsyncConfig.java
  backend/src/main/java/com/backend/global/config/MailConfig.java
  backend/src/main/java/com/backend/global/email/service/EmailService.java
  backend/src/main/java/com/backend/global/email/service/EmailServiceImpl.java
  backend/src/test/java/com/backend/domain/fishencyclopedia/repository/FishEncyclopediaRepositoryTest.java
  backend/src/test/java/com/backend/domain/fishingtrippost/controller/FishingTripPostControllerTest.java
  backend/src/test/java/com/backend/domain/fishingtrippost/repository/FishingTripPostRepositoryTest.java
  backend/src/test/java/com/backend/domain/fishingtrippost/service/FishingTripPostServiceTest.java
  backend/src/test/java/com/backend/domain/fishingtriprecruitment/repository/FishingTripRecruitmentRepositoryTest.java
  backend/src/test/java/com/backend/domain/fishingtriprecruitment/service/FishingTripRecruitmentServiceTest.java
  backend/src/test/java/com/backend/domain/fishpoint/repository/FishPointRepositoryTest.java
  backend/src/test/java/com/backend/domain/member/repository/MemberRepositoryTest.java
  backend/src/test/java/com/backend/global/util/BaseTest.java
Labels: enhancement

#56 MIKKI-105
  backend/src/main/java/com/backend/domain/fishpoint/controller/FishPointController.java
  backend/src/main/java/com/backend/domain/region/controller/RegionController.java
  backend/src/main/java/com/backend/domain/region/converter/RegionConverter.java
  backend/src/main/java/com/backend/domain/region/dto/response/RegionResponse.java
  backend/src/main/java/com/backend/domain/region/repository/RegionJpaRepository.java
  backend/src/main/java/com/backend/domain/region/repository/RegionRepository.java
  backend/src/main/java/com/backend/domain/region/repository/RegionRepositoryImpl.java
  backend/src/main/java/com/backend/domain/region/service/RegionService.java
  backend/src/main/java/com/backend/domain/region/service/RegionServiceImpl.java
Labels: enhancement

#58 MIKKI-149
  backend/src/main/java/com/backend/domain/ship/controller/ShipController.java
  backend/src/main/java/com/backend/domain/ship/dto/response/ShipResponse.java
  backend/src/main/java/com/backend/domain/ship/repository/ShipQueryRepository.java
  backend/src/main/java/com/backend/domain/ship/repository/ShipRepository.java
  backend/src/main/java/com/backend/domain/ship/repository/ShipRepositoryImpl.java
  backend/src/main/java/com/backend/domain/ship/service/ShipService.java
  backend/src/main/java/com/backend/domain/ship/service/ShipServiceImpl.java
  backend/src/main/java/com/backend/global/dto/request/GlobalRequest.java
  backend/src/test/java/com/backend/domain/ship/controller/ShipControllerTest.java
  backend/src/test/java/com/backend/domain/ship/repository/ShipRepositoryTest.java
  backend/src/test/java/com/backend/domain/ship/service/ShipServiceTest.java
Labels: enhancement

#57 MIKKI-138-1
  backend/src/main/java/com/backend/domain/fish/dto/FishResponse.java
  backend/src/main/java/com/backend/domain/fish/repository/FishQueryRepository.java
  backend/src/main/java/com/backend/domain/fish/repository/FishRepository.java
  backend/src/main/java/com/backend/domain/fish/repository/FishRepositoryImpl.java
  backend/src/main/java/com/backend/domain/reservation/controller/ReservationController.java
  backend/src/main/java/com/backend/domain/reservation/repository/ReservationQueryRepository.java
  backend/src/main/java/com/backend/domain/reservationdate/converter/ReservationDateConverter.java
  backend/src/main/java/com/backend/domain/reservationdate/service/ReservationDateServiceImpl.java
  backend/src/main/java/com/backend/domain/shipfishingpost/converter/ShipFishingPostConverter.java
  backend/src/main/java/com/backend/domain/shipfishingpost/dto/request/ShipFishingPostRequest.java
  backend/src/main/java/com/backend/domain/shipfishingpost/dto/response/ShipFishingPostResponse.java
  backend/src/main/java/com/backend/domain/shipfishingpost/repository/ShipFishingPostQueryRepository.java
  backend/src/main/java/com/backend/domain/shipfishingpost/service/ShipFishingPostServiceImpl.java
  backend/src/test/java/com/backend/domain/reservation/repository/ReservationRepositoryTest.java
  backend/src/test/java/com/backend/domain/reservationdate/repository/ReservationDateRepositoryTest.java
  backend/src/test/java/com/backend/domain/shipfishingpost/repository/ShipFishingPostRepositoryTest.java
  backend/src/test/java/com/backend/domain/shipfishingpost/service/ShipFishingPostServiceTest.java
Labels: refactor

#59 MIKKI-151
  backend/src/main/java/com/backend/domain/fishingtrippost/controller/FishingTripPostController.java
  backend/src/main/java/com/backend/domain/fishingtrippost/converter/FishingTripPostConverter.java
  backend/src/main/java/com/backend/domain/fishingtrippost/domain/PostStatus.java
  backend/src/main/java/com/backend/domain/fishingtrippost/dto/request/FishingTripPostRequest.java
  backend/src/main/java/com/backend/domain/fishingtrippost/dto/response/FishingTripPostResponse.java
  backend/src/main/java/com/backend/domain/fishingtrippost/entity/FishingTripPost.java
  backend/src/main/java/com/backend/domain/fishingtrippost/repository/FishingTripPostQueryRepository.java
  backend/src/main/java/com/backend/domain/fishingtrippost/repository/FishingTripPostRepository.java
  backend/src/main/java/com/backend/domain/fishingtrippost/repository/FishingTripPostRepositoryImpl.java
  backend/src/main/java/com/backend/domain/fishingtrippost/service/FishingTripPostService.java
  backend/src/main/java/com/backend/domain/fishingtrippost/service/FishingTripPostServiceImpl.java
  backend/src/main/java/com/backend/global/dto/request/GlobalRequest.java
  backend/src/main/java/com/backend/global/storage/repository/StorageRepository.java
  backend/src/main/java/com/backend/global/storage/repository/StorageRepositoryImpl.java
  backend/src/test/java/com/backend/domain/fishingtrippost/controller/FishingTripPostControllerTest.java
  backend/src/test/java/com/backend/domain/fishingtrippost/repository/FishingTripPostRepositoryTest.java
  backend/src/test/java/com/backend/domain/fishingtrippost/service/FishingTripPostServiceTest.java
Labels: enhancement

#61 MIKKI-105
  backend/src/main/java/com/backend/domain/fishencyclopedia/repository/FishEncyclopediaQueryRepository.java
  backend/src/main/java/com/backend/domain/fishencyclopedia/repository/FishEncyclopediaRepository.java
  backend/src/main/java/com/backend/domain/fishencyclopedia/repository/FishEncyclopediaRepositoryImpl.java
  backend/src/main/java/com/backend/domain/fishpoint/controller/FishPointController.java
  backend/src/main/java/com/backend/domain/fishpoint/converter/FishPointConverter.java
  backend/src/main/java/com/backend/domain/fishpoint/dto/response/FishPointResponse.java
  backend/src/main/java/com/backend/domain/fishpoint/repository/FishPointRepository.java
  backend/src/main/java/com/backend/domain/fishpoint/repository/FishPointRepositoryImpl.java
  backend/src/main/java/com/backend/domain/fishpoint/service/FishPointService.java
  backend/src/main/java/com/backend/domain/fishpoint/service/FishPointServiceImpl.java
  backend/src/main/java/com/backend/domain/fishpointsummary/converter/FishPointSummaryConverter.java
  backend/src/main/java/com/backend/domain/fishpointsummary/dto/response/FishPointSummaryResponse.java
  backend/src/main/java/com/backend/domain/fishpointsummary/entity/FishPointSummary.java
  backend/src/main/java/com/backend/domain/fishpointsummary/repository/FishPointSummaryJpaRepository.java
  backend/src/main/java/com/backend/domain/fishpointsummary/repository/FishPointSummaryQueryRepository.java
  backend/src/main/java/com/backend/domain/fishpointsummary/repository/FishPointSummaryRepository.java
  backend/src/main/java/com/backend/domain/fishpointsummary/repository/FishPointSummaryRepositoryImpl.java
  backend/src/main/java/com/backend/domain/fishpointsummary/scheduler/FishPointSummaryScheduler.java
  backend/src/main/java/com/backend/domain/fishpointsummary/service/FishPointSummaryService.java
  backend/src/main/java/com/backend/domain/fishpointsummary/service/FishPointSummaryServiceImpl.java
  backend/src/main/java/com/backend/domain/region/converter/RegionConverter.java
  backend/src/main/java/com/backend/domain/region/dto/response/RegionResponse.java
  backend/src/main/java/com/backend/domain/region/entity/Region.java
  backend/src/test/java/com/backend/domain/fishpoint/controller/FishPointControllerTest.java
  backend/src/test/java/com/backend/domain/fishpoint/repository/FishPointRepositoryTest.java
  backend/src/test/java/com/backend/domain/fishpoint/service/FishPointServiceTest.java
  backend/src/test/java/com/backend/domain/fishpointsummary/repository/FishPointSummaryRepositoryTest.java
  backend/src/test/java/com/backend/domain/fishpointsummary/service/FishPointSummaryServiceTest.java
  backend/src/test/java/com/backend/global/util/BaseTest.java
Labels: enhancement, refactor

#62 MIKKI-156
  backend/src/main/java/com/backend/domain/ship/controller/ShipController.java
  backend/src/main/java/com/backend/domain/ship/exception/ShipErrorCode.java
  backend/src/main/java/com/backend/domain/ship/exception/ShipException.java
  backend/src/main/java/com/backend/domain/ship/repository/ShipRepository.java
  backend/src/main/java/com/backend/domain/ship/repository/ShipRepositoryImpl.java
  backend/src/main/java/com/backend/domain/ship/service/ShipService.java
  backend/src/main/java/com/backend/domain/ship/service/ShipServiceImpl.java
  backend/src/main/java/com/backend/domain/shipfishingpost/repository/ShipFishingPostJpaRepository.java
  backend/src/main/java/com/backend/domain/shipfishingpost/repository/ShipFishingPostRepository.java
  backend/src/main/java/com/backend/domain/shipfishingpost/repository/ShipFishingPostRepositoryImpl.java
  backend/src/test/java/com/backend/domain/ship/controller/ShipControllerTest.java
  backend/src/test/java/com/backend/domain/ship/repository/ShipRepositoryTest.java
  backend/src/test/java/com/backend/domain/ship/service/ShipServiceTest.java
Labels: enhancement

#63 MIKKI-120
  backend/src/main/java/com/backend/domain/fishingtrippost/entity/FishingTripPost.java
  backend/src/main/java/com/backend/domain/fishingtrippost/repository/FishingTripPostQueryRepository.java
  backend/src/main/java/com/backend/domain/fishingtrippost/repository/FishingTripPostRepository.java
  backend/src/main/java/com/backend/domain/fishingtrippost/repository/FishingTripPostRepositoryImpl.java
  backend/src/main/java/com/backend/domain/fishpointsummary/service/FishPointSummaryServiceImpl.java
  backend/src/main/java/com/backend/domain/like/controller/LikeController.java
  backend/src/main/java/com/backend/domain/like/converter/LikeConverter.java
  backend/src/main/java/com/backend/domain/like/domain/LikeTargetType.java
  backend/src/main/java/com/backend/domain/like/dto/request/LikeRequest.java
  backend/src/main/java/com/backend/domain/like/dto/response/LikeResponse.java
  backend/src/main/java/com/backend/domain/like/entity/Like.java
  backend/src/main/java/com/backend/domain/like/repository/LikeJpaRepository.java
  backend/src/main/java/com/backend/domain/like/repository/LikeQueryRepository.java
  backend/src/main/java/com/backend/domain/like/repository/LikeRepository.java
  backend/src/main/java/com/backend/domain/like/repository/LikeRepositoryImpl.java
  backend/src/main/java/com/backend/domain/like/scheduler/LikeCleanUpScheduler.java
  backend/src/main/java/com/backend/domain/like/scheduler/LikeSyncScheduler.java
  backend/src/main/java/com/backend/domain/like/service/LikeCacheService.java
  backend/src/main/java/com/backend/domain/like/service/LikeService.java
  backend/src/main/java/com/backend/domain/like/service/LikeServiceImpl.java
  backend/src/main/java/com/backend/domain/likes/entity/Likes.java
  backend/src/main/java/com/backend/domain/shipfishingpost/entity/ShipFishingPost.java
  backend/src/main/java/com/backend/domain/shipfishingpost/repository/ShipFishingPostQueryRepository.java
  backend/src/main/java/com/backend/domain/shipfishingpost/repository/ShipFishingPostRepository.java
  backend/src/main/java/com/backend/domain/shipfishingpost/repository/ShipFishingPostRepositoryImpl.java
  backend/src/main/java/com/backend/global/config/RedisConfig.java
  backend/src/main/java/com/backend/global/util/RedisUtil.java
  backend/src/test/java/com/backend/domain/shipfishingpost/repository/ShipFishingPostRepositoryTest.java
Labels: enhancement

#65 MIKKI-126
  backend/src/main/java/com/backend/domain/fishingtrippost/controller/FishingTripPostController.java
  backend/src/main/java/com/backend/domain/fishingtrippost/converter/FishingTripPostConverter.java
  backend/src/main/java/com/backend/domain/fishingtrippost/dto/response/FishingTripPostResponse.java
  backend/src/main/java/com/backend/domain/fishingtrippost/repository/FishingTripPostQueryRepository.java
  backend/src/main/java/com/backend/domain/fishingtrippost/repository/FishingTripPostRepository.java
  backend/src/main/java/com/backend/domain/fishingtrippost/repository/FishingTripPostRepositoryImpl.java
  backend/src/main/java/com/backend/domain/fishingtrippost/service/FishingTripPostService.java
  backend/src/main/java/com/backend/domain/fishingtrippost/service/FishingTripPostServiceImpl.java
  backend/src/main/java/com/backend/global/config/SecurityConfig.java
  backend/src/test/java/com/backend/domain/fishingtrippost/controller/FishingTripPostControllerTest.java
  backend/src/test/java/com/backend/domain/fishingtrippost/repository/FishingTripPostRepositoryTest.java
  backend/src/test/java/com/backend/domain/fishingtrippost/service/FishingTripPostServiceTest.java
Labels: enhancement

#64 MIKKI-159
  backend/src/main/java/com/backend/domain/comment/controller/CommentController.java
  backend/src/main/java/com/backend/domain/comment/converter/CommentConverter.java
  backend/src/main/java/com/backend/domain/comment/dto/request/CommentRequest.java
  backend/src/main/java/com/backend/domain/comment/entity/Comment.java
  backend/src/main/java/com/backend/domain/comment/exception/CommentErrorCode.java
  backend/src/main/java/com/backend/domain/comment/exception/CommentExpection.java
  backend/src/main/java/com/backend/domain/comment/repository/CommentJpaRepository.java
  backend/src/main/java/com/backend/domain/comment/repository/CommentQueryRepository.java
  backend/src/main/java/com/backend/domain/comment/repository/CommentRepository.java
  backend/src/main/java/com/backend/domain/comment/repository/CommentRepositoryImpl.java
  backend/src/main/java/com/backend/domain/comment/service/CommentService.java
  backend/src/main/java/com/backend/domain/comment/service/CommentServiceImpl.java
  backend/src/test/java/com/backend/domain/comment/controller/CommentControllerTest.java
  backend/src/test/java/com/backend/domain/comment/repository/CommentRepositoryTest.java
  backend/src/test/java/com/backend/domain/comment/service/CommentServiceTest.java
Labels: enhancement

#66 MIKKI-160
  backend/src/main/java/com/backend/domain/fishencyclopedia/controller/FishEncyclopediaController.java
  backend/src/main/java/com/backend/domain/fishencyclopedia/repository/FishEncyclopediaQueryRepository.java
  backend/src/main/java/com/backend/domain/fishencyclopedia/repository/FishEncyclopediaRepository.java
  backend/src/main/java/com/backend/domain/fishencyclopedia/repository/FishEncyclopediaRepositoryImpl.java
  backend/src/main/java/com/backend/domain/fishencyclopedia/service/FishEncyclopediaService.java
  backend/src/main/java/com/backend/domain/fishencyclopedia/service/FishEncyclopediaServiceImpl.java
  backend/src/test/java/com/backend/domain/fishencyclopedia/controller/FishEncyclopediaControllerTest.java
  backend/src/test/java/com/backend/domain/fishencyclopedia/repository/FishEncyclopediaRepositoryTest.java
  backend/src/test/java/com/backend/domain/fishencyclopedia/service/FishEncyclopediaServiceTest.java
Labels: enhancement

#67 MIKKI-163
  backend/src/main/java/com/backend/domain/fishingtrippost/controller/FishingTripPostController.java
  backend/src/main/java/com/backend/domain/fishingtrippost/converter/FishingTripPostConverter.java
  backend/src/main/java/com/backend/domain/fishingtrippost/dto/response/FishingTripPostResponse.java
  backend/src/main/java/com/backend/domain/fishingtrippost/entity/FishingTripPost.java
  backend/src/main/java/com/backend/domain/fishingtrippost/service/FishingTripPostService.java
  backend/src/main/java/com/backend/domain/fishingtrippost/service/FishingTripPostServiceImpl.java
  backend/src/main/java/com/backend/global/config/SecurityConfig.java
  backend/src/test/java/com/backend/domain/comment/controller/CommentControllerTest.java
  backend/src/test/java/com/backend/domain/fishingtrippost/controller/FishingTripPostControllerTest.java
  backend/src/test/java/com/backend/domain/fishingtrippost/repository/FishingTripPostRepositoryTest.java
  backend/src/test/java/com/backend/domain/fishingtrippost/service/FishingTripPostServiceTest.java
  backend/src/test/java/com/backend/domain/shipfishingpost/repository/ShipFishingPostRepositoryTest.java
Labels: enhancement

#70 MIKKI-166
  backend/src/main/java/com/backend/domain/chat/room/converter/RoomConverter.java
  backend/src/main/java/com/backend/domain/chat/room/entity/Room.java
  backend/src/main/java/com/backend/domain/chat/room/entity/Status.java
  backend/src/main/java/com/backend/domain/chat/room/entity/TargetType.java
  backend/src/main/java/com/backend/domain/chat/room/repository/RoomJpaRepository.java
  backend/src/main/java/com/backend/domain/chat/room/repository/RoomQueryRepository.java
  backend/src/main/java/com/backend/domain/chat/room/repository/RoomRepository.java
  backend/src/main/java/com/backend/domain/chat/room/repository/RoomRepositoryImpl.java
  backend/src/main/java/com/backend/domain/chat/room/service/RoomService.java
  backend/src/main/java/com/backend/domain/chat/room/service/RoomServiceImpl.java
  backend/src/main/java/com/backend/domain/fishingtrippost/service/FishingTripPostServiceImpl.java
  backend/src/test/java/com/backend/domain/chat/room/repository/RoomRepositoryTest.java
  backend/src/test/java/com/backend/domain/chat/room/service/RoomServiceTest.java
  backend/src/test/java/com/backend/domain/fishingtrippost/service/FishingTripPostServiceTest.java
Labels: enhancement

#72 MIKKI-165
  backend/src/main/java/com/backend/domain/comment/dto/response/CommentResponse.java
  backend/src/main/java/com/backend/domain/comment/repository/CommentQueryRepository.java
Labels: enhancement

#71 MIKKI-167
  backend/src/main/java/com/backend/domain/fishingtrippost/controller/FishingTripPostController.java
  backend/src/main/java/com/backend/domain/fishingtrippost/repository/FishingTripPostRepository.java
  backend/src/main/java/com/backend/domain/fishingtrippost/repository/FishingTripPostRepositoryImpl.java
  backend/src/main/java/com/backend/domain/fishingtrippost/service/FishingTripPostService.java
  backend/src/main/java/com/backend/domain/fishingtrippost/service/FishingTripPostServiceImpl.java
  backend/src/main/java/com/backend/domain/fishingtriprecruitment/repository/FishingTripRecruitmentQueryRepository.java
  backend/src/main/java/com/backend/domain/fishingtriprecruitment/repository/FishingTripRecruitmentRepository.java
  backend/src/main/java/com/backend/domain/fishingtriprecruitment/repository/FishingTripRecruitmentRepositoryImpl.java
  backend/src/test/java/com/backend/domain/fishingtrippost/repository/FishingTripPostRepositoryTest.java
  backend/src/test/java/com/backend/domain/fishingtriprecruitment/repository/FishingTripRecruitmentRepositoryTest.java
Labels: enhancement

#76 MIKKI-172
  backend/src/main/java/com/backend/domain/comment/service/CommentServiceImpl.java
  backend/src/main/java/com/backend/domain/fishingtrippost/controller/FishingTripPostController.java
  backend/src/main/java/com/backend/domain/fishingtrippost/converter/FishingTripPostConverter.java
  backend/src/main/java/com/backend/domain/fishingtrippost/dto/response/FishingTripPostResponse.java
  backend/src/main/java/com/backend/domain/fishingtrippost/entity/FishingTripPost.java
  backend/src/main/java/com/backend/domain/fishingtrippost/repository/FishingTripPostQueryRepository.java
  backend/src/main/java/com/backend/domain/fishingtrippost/repository/FishingTripPostRepository.java
  backend/src/main/java/com/backend/domain/fishingtrippost/repository/FishingTripPostRepositoryImpl.java
  backend/src/main/java/com/backend/domain/fishingtrippost/service/FishingTripPostService.java
  backend/src/main/java/com/backend/domain/fishingtrippost/service/FishingTripPostServiceImpl.java
  backend/src/test/java/com/backend/domain/comment/service/CommentServiceTest.java
  backend/src/test/java/com/backend/domain/fishingtrippost/controller/FishingTripPostControllerTest.java
  backend/src/test/java/com/backend/domain/fishingtrippost/repository/FishingTripPostRepositoryTest.java
  backend/src/test/java/com/backend/domain/fishingtrippost/service/FishingTripPostServiceTest.java
Labels: enhancement

#75 MIKKI-171
  backend/build.gradle
  backend/src/main/java/com/backend/domain/chat/message/controller/MessageController.java
  backend/src/main/java/com/backend/domain/chat/message/converter/MessageConverter.java
  backend/src/main/java/com/backend/domain/chat/message/dto/request/MessageRequest.java
  backend/src/main/java/com/backend/domain/chat/message/dto/response/MessageResponse.java
  backend/src/main/java/com/backend/domain/chat/message/entity/Message.java
  backend/src/main/java/com/backend/domain/chat/message/entity/MessageType.java
  backend/src/main/java/com/backend/domain/chat/message/repository/MessageMongoRepository.java
  backend/src/main/java/com/backend/domain/chat/message/repository/MessageQueryRepository.java
  backend/src/main/java/com/backend/domain/chat/message/repository/MessageRepository.java
  backend/src/main/java/com/backend/domain/chat/message/repository/MessageRepositoryImpl.java
  backend/src/main/java/com/backend/domain/chat/message/service/MessageService.java
  backend/src/main/java/com/backend/domain/chat/message/service/MessageServiceImpl.java
  backend/src/main/java/com/backend/domain/member/dto/MemberResponse.java
  backend/src/main/java/com/backend/domain/member/service/MemberService.java
  backend/src/main/java/com/backend/domain/member/service/MemberServiceImpl.java
  backend/src/main/java/com/backend/global/config/MongoAuditingConfig.java
  backend/src/main/java/com/backend/global/config/WebSocketConfig.java
  backend/src/main/java/com/backend/global/storage/service/S3StorageService.java
  backend/src/main/java/com/backend/global/storage/service/StorageService.java
  backend/src/main/java/com/backend/global/websocket/JwtHandshakeInterceptor.java
  backend/src/main/java/com/backend/global/websocket/StompCommandInterceptor.java
  backend/src/test/java/com/backend/domain/comment/repository/CommentRepositoryTest.java
  backend/src/test/java/com/backend/domain/reservation/repository/ReservationRepositoryTest.java
  backend/src/test/java/com/backend/domain/reservationdate/repository/ReservationDateRepositoryTest.java
  backend/src/test/java/com/backend/domain/ship/repository/ShipRepositoryTest.java
  backend/src/test/java/com/backend/domain/shipfishingpost/repository/ShipFishingPostRepositoryTest.java
Labels: enhancement

#77 MIKKI-125
  backend/src/main/java/com/backend/domain/fishingtrippost/repository/FishingTripPostQueryRepository.java
  backend/src/main/java/com/backend/domain/fishingtrippost/repository/FishingTripPostRepository.java
  backend/src/main/java/com/backend/domain/fishingtrippost/repository/FishingTripPostRepositoryImpl.java
  backend/src/main/java/com/backend/domain/like/entity/Like.java
  backend/src/main/java/com/backend/domain/like/scheduler/LikeSyncScheduler.java
  backend/src/main/java/com/backend/domain/like/service/LikeCacheService.java
  backend/src/main/java/com/backend/domain/like/service/LikeServiceImpl.java
  backend/src/main/java/com/backend/domain/shipfishingpost/repository/ShipFishingPostQueryRepository.java
  backend/src/main/java/com/backend/domain/shipfishingpost/repository/ShipFishingPostRepository.java
  backend/src/main/java/com/backend/domain/shipfishingpost/repository/ShipFishingPostRepositoryImpl.java
  backend/src/main/java/com/backend/global/util/RedisUtil.java
Labels: refactor

#78 MIKKI-180
  backend/src/main/java/com/backend/domain/fishingtrippost/controller/FishingTripPostController.java
  backend/src/main/java/com/backend/domain/fishingtrippost/repository/FishingTripPostQueryRepository.java
  backend/src/main/java/com/backend/domain/fishingtrippost/repository/FishingTripPostRepository.java
  backend/src/main/java/com/backend/domain/fishingtrippost/repository/FishingTripPostRepositoryImpl.java
  backend/src/main/java/com/backend/domain/fishingtrippost/service/FishingTripPostService.java
  backend/src/main/java/com/backend/domain/fishingtrippost/service/FishingTripPostServiceImpl.java
  backend/src/test/java/com/backend/domain/fishingtrippost/controller/FishingTripPostControllerTest.java
  backend/src/test/java/com/backend/domain/fishingtrippost/repository/FishingTripPostRepositoryTest.java
  backend/src/test/java/com/backend/domain/fishingtrippost/service/FishingTripPostServiceTest.java
Labels: enhancement

#79 MIKKI-177
  backend/src/main/java/com/backend/domain/activityhistory/converter/ActivityHistoryConverter.java
  backend/src/main/java/com/backend/domain/activityhistory/domain/ActivityType.java
  backend/src/main/java/com/backend/domain/activityhistory/entity/ActivityHistory.java
  backend/src/main/java/com/backend/domain/activityhistory/repository/ActivityHistoryJpaRepository.java
  backend/src/main/java/com/backend/domain/activityhistory/repository/ActivityHistoryRepository.java
  backend/src/main/java/com/backend/domain/activityhistory/repository/ActivityHistoryRepositoryImpl.java
  backend/src/main/java/com/backend/domain/activityhistory/service/ActivityHistoryService.java
  backend/src/main/java/com/backend/domain/activityhistory/service/ActivityHistoryServiceImpl.java
  backend/src/main/java/com/backend/domain/activityhistory/util/ActivityDescriptionBuilder.java
  backend/src/main/java/com/backend/domain/fish/repository/FishQueryRepository.java
  backend/src/main/java/com/backend/domain/fish/repository/FishRepository.java
  backend/src/main/java/com/backend/domain/fish/repository/FishRepositoryImpl.java
  backend/src/main/java/com/backend/domain/fishencyclopedia/service/FishEncyclopediaServiceImpl.java
  backend/src/main/java/com/backend/domain/fishingtrippost/service/FishingTripPostServiceImpl.java
  backend/src/main/java/com/backend/domain/fishpoint/repository/FishPointQueryRepository.java
  backend/src/main/java/com/backend/domain/fishpoint/repository/FishPointRepository.java
  backend/src/main/java/com/backend/domain/fishpoint/repository/FishPointRepositoryImpl.java
  backend/src/main/java/com/backend/domain/reservation/service/ReservationServiceImpl.java
  backend/src/main/java/com/backend/domain/shipfishingpost/repository/ShipFishingPostQueryRepository.java
  backend/src/main/java/com/backend/domain/shipfishingpost/repository/ShipFishingPostRepository.java
  backend/src/main/java/com/backend/domain/shipfishingpost/repository/ShipFishingPostRepositoryImpl.java
  backend/src/test/java/com/backend/domain/activityhistory/repository/ActivityHistoryRepositoryTest.java
  backend/src/test/java/com/backend/domain/activityhistory/service/ActivityHistoryServiceTest.java
  backend/src/test/java/com/backend/domain/fishencyclopedia/service/FishEncyclopediaServiceTest.java
  backend/src/test/java/com/backend/domain/fishingtrippost/service/FishingTripPostServiceTest.java
  backend/src/test/java/com/backend/domain/reservation/service/ReservationServiceTest.java
  backend/src/test/java/com/backend/domain/ship/repository/ShipRepositoryTest.java
Labels: enhancement

#80 MIKKI-185
  backend/src/main/java/com/backend/domain/comment/controller/CommentController.java
  backend/src/main/java/com/backend/domain/comment/service/CommentServiceImpl.java
  backend/src/test/java/com/backend/domain/captain/repository/CaptainRepositoryTest.java
  backend/src/test/java/com/backend/domain/comment/repository/CommentRepositoryTest.java
  backend/src/test/java/com/backend/domain/comment/service/CommentServiceTest.java
  backend/src/test/java/com/backend/domain/fish/repository/FishRepositoryTest.java
  backend/src/test/java/com/backend/domain/fishencyclopedia/repository/FishEncyclopediaRepositoryTest.java
  backend/src/test/java/com/backend/domain/fishingtrippost/repository/FishingTripPostRepositoryTest.java
  backend/src/test/java/com/backend/domain/fishingtriprecruitment/repository/FishingTripRecruitmentRepositoryTest.java
  backend/src/test/java/com/backend/domain/fishpoint/repository/FishPointRepositoryTest.java
  backend/src/test/java/com/backend/domain/fishpointsummary/repository/FishPointSummaryRepositoryTest.java
  backend/src/test/java/com/backend/domain/member/repository/MemberRepositoryTest.java
  backend/src/test/java/com/backend/domain/reservation/repository/ReservationRepositoryTest.java
  backend/src/test/java/com/backend/domain/reservationdate/repository/ReservationDateRepositoryTest.java
  backend/src/test/java/com/backend/domain/review/repository/ReviewRepositoryTest.java
  backend/src/test/java/com/backend/domain/ship/repository/ShipRepositoryTest.java
Labels: bug

#81 MIKKI-181
  backend/src/main/java/com/backend/domain/reservation/repository/ReservationQueryRepository.java
  backend/src/main/java/com/backend/domain/shipfishingpost/controller/ShipFishingPostController.java
  backend/src/main/java/com/backend/domain/shipfishingpost/dto/response/ShipFishingPostResponse.java
  backend/src/main/java/com/backend/domain/shipfishingpost/repository/ShipFishingPostQueryRepository.java
  backend/src/main/java/com/backend/domain/shipfishingpost/repository/ShipFishingPostRepository.java
  backend/src/main/java/com/backend/domain/shipfishingpost/repository/ShipFishingPostRepositoryImpl.java
  backend/src/main/java/com/backend/domain/shipfishingpost/service/ShipFishingPostService.java
  backend/src/main/java/com/backend/domain/shipfishingpost/service/ShipFishingPostServiceImpl.java
  backend/src/test/java/com/backend/domain/reservationdate/repository/ReservationDateRepositoryTest.java
  backend/src/test/java/com/backend/domain/shipfishingpost/repository/ShipFishingPostRepositoryTest.java
  backend/src/test/java/com/backend/domain/shipfishingpost/service/ShipFishingPostServiceTest.java
Labels: enhancement

#82 MIKKI-183
  backend/src/main/java/com/backend/domain/fishingtrippost/controller/FishingTripPostController.java
  backend/src/main/java/com/backend/domain/fishingtrippost/dto/response/FishingTripPostResponse.java
  backend/src/main/java/com/backend/domain/fishingtrippost/repository/FishingTripPostQueryRepository.java
  backend/src/main/java/com/backend/domain/fishingtrippost/repository/FishingTripPostRepository.java
  backend/src/main/java/com/backend/domain/fishingtrippost/repository/FishingTripPostRepositoryImpl.java
  backend/src/main/java/com/backend/domain/fishingtrippost/service/FishingTripPostService.java
  backend/src/main/java/com/backend/domain/fishingtrippost/service/FishingTripPostServiceImpl.java
  backend/src/main/java/com/backend/global/config/RedisConfig.java
  backend/src/main/java/com/backend/global/config/SecurityConfig.java
  backend/src/test/java/com/backend/domain/fishingtrippost/controller/FishingTripPostControllerTest.java
  backend/src/test/java/com/backend/domain/fishingtrippost/repository/FishingTripPostRepositoryTest.java
  backend/src/test/java/com/backend/domain/fishingtrippost/service/FishingTripPostServiceTest.java
Labels: enhancement

#83 MIKKI-184
  backend/src/main/java/com/backend/domain/activityhistory/controller/ActivityHistoryController.java
  backend/src/main/java/com/backend/domain/activityhistory/converter/ActivityHistoryConverter.java
  backend/src/main/java/com/backend/domain/activityhistory/domain/ActivityType.java
  backend/src/main/java/com/backend/domain/activityhistory/dto/request/ActivityHistoryRequest.java
  backend/src/main/java/com/backend/domain/activityhistory/dto/response/ActivityHistoryResponse.java
  backend/src/main/java/com/backend/domain/activityhistory/entity/ActivityHistory.java
  backend/src/main/java/com/backend/domain/activityhistory/repository/ActivityHistoryQueryRepository.java
  backend/src/main/java/com/backend/domain/activityhistory/repository/ActivityHistoryRepository.java
  backend/src/main/java/com/backend/domain/activityhistory/repository/ActivityHistoryRepositoryImpl.java
  backend/src/main/java/com/backend/domain/activityhistory/service/ActivityHistoryService.java
  backend/src/main/java/com/backend/domain/activityhistory/service/ActivityHistoryServiceImpl.java
  backend/src/test/java/com/backend/domain/activityhistory/controller/ActivityHistoryControllerTest.java
  backend/src/test/java/com/backend/domain/activityhistory/repository/ActivityHistoryRepositoryTest.java
  backend/src/test/java/com/backend/domain/activityhistory/service/ActivityHistoryServiceTest.java
Labels: enhancement

#84 MIKKI-190
  backend/src/main/java/com/backend/domain/member/service/MemberServiceImpl.java
Labels: enhancement

#86 MIKKI-184
  backend/src/main/java/com/backend/domain/activityhistory/controller/ActivityHistoryController.java
Labels: enhancement

#85 MIKKI-131
  backend/src/main/java/com/backend/domain/review/repository/ReviewJpaRepository.java
  backend/src/main/java/com/backend/domain/review/repository/ReviewQueryRepository.java
  backend/src/main/java/com/backend/domain/review/repository/ReviewRepository.java
  backend/src/main/java/com/backend/domain/review/repository/ReviewRepositoryImpl.java
  backend/src/main/java/com/backend/domain/shipfishingpost/service/ShipFishingPostServiceImpl.java
  backend/src/test/java/com/backend/domain/reservationdate/repository/ReservationDateRepositoryTest.java
  backend/src/test/java/com/backend/domain/review/repository/ReviewRepositoryTest.java
  backend/src/test/java/com/backend/domain/shipfishingpost/repository/ShipFishingPostRepositoryTest.java
  backend/src/test/java/com/backend/domain/shipfishingpost/service/ShipFishingPostServiceTest.java
Labels: enhancement

#89 MIKKI-190
  backend/src/main/java/com/backend/global/auth/oauth2/service/CustomOAuth2UserService.java
Labels: enhancement

#88 MIKKI-191
  backend/src/main/java/com/backend/domain/activityhistory/entity/ActivityHistory.java
  backend/src/main/java/com/backend/domain/activityhistory/repository/ActivityHistoryQueryRepository.java
  backend/src/main/java/com/backend/domain/activityhistory/repository/ActivityHistoryRepository.java
  backend/src/main/java/com/backend/domain/activityhistory/repository/ActivityHistoryRepositoryImpl.java
  backend/src/main/java/com/backend/domain/activityhistory/scheduler/ActivityHistoryScheduler.java
  backend/src/test/java/com/backend/domain/activityhistory/repository/ActivityHistoryRepositoryTest.java
Labels: enhancement

#91 MIKKI-193
  backend/src/main/java/com/backend/domain/fishingtrippost/converter/FishingTripPostConverter.java
  backend/src/main/java/com/backend/domain/fishingtrippost/dto/response/FishingTripPostResponse.java
  backend/src/main/java/com/backend/domain/fishingtrippost/repository/FishingTripPostQueryRepository.java
  backend/src/main/java/com/backend/domain/like/converter/LikeConverter.java
  backend/src/main/java/com/backend/domain/like/entity/Like.java
  backend/src/main/java/com/backend/domain/like/repository/LikeQueryRepository.java
  backend/src/main/java/com/backend/domain/like/scheduler/LikeCleanUpScheduler.java
  backend/src/main/java/com/backend/domain/like/scheduler/LikeSyncScheduler.java
  backend/src/main/java/com/backend/global/util/QuerydslUtil.java
  backend/src/test/java/com/backend/domain/fishingtrippost/service/FishingTripPostServiceTest.java
Labels: enhancement

#92 MIKKI-194
  backend/src/main/java/com/backend/domain/fishingtrippost/service/FishingTripPostServiceImpl.java
  backend/src/main/java/com/backend/domain/like/repository/LikeJpaRepository.java
  backend/src/main/java/com/backend/domain/like/repository/LikeRepository.java
  backend/src/main/java/com/backend/domain/like/repository/LikeRepositoryImpl.java
Labels: enhancement

#93 MIKKI-196
  backend/src/main/java/com/backend/domain/like/controller/LikeController.java
  backend/src/main/java/com/backend/domain/like/entity/Like.java
  backend/src/main/java/com/backend/domain/like/repository/LikeQueryRepository.java
  backend/src/main/java/com/backend/domain/like/repository/LikeRepository.java
  backend/src/main/java/com/backend/domain/like/repository/LikeRepositoryImpl.java
  backend/src/main/java/com/backend/domain/like/service/LikeService.java
  backend/src/main/java/com/backend/domain/like/service/LikeServiceImpl.java
Labels: enhancement

#94 MIKKI-189
  backend/src/main/java/com/backend/domain/chat/controller/ChatController.java
  backend/src/main/java/com/backend/domain/chat/dto/request/ChatRequest.java
  backend/src/main/java/com/backend/domain/chat/dto/response/ChatResponse.java
  backend/src/main/java/com/backend/domain/chat/message/controller/MessageController.java
  backend/src/main/java/com/backend/domain/chat/message/converter/MessageConverter.java
  backend/src/main/java/com/backend/domain/chat/message/dto/response/MessageResponse.java
  backend/src/main/java/com/backend/domain/chat/message/entity/Message.java
  backend/src/main/java/com/backend/domain/chat/message/repository/MessageQueryRepository.java
  backend/src/main/java/com/backend/domain/chat/message/repository/MessageRepository.java
  backend/src/main/java/com/backend/domain/chat/message/repository/MessageRepositoryImpl.java
  backend/src/main/java/com/backend/domain/chat/message/service/MessageService.java
  backend/src/main/java/com/backend/domain/chat/message/service/MessageServiceImpl.java
  backend/src/main/java/com/backend/domain/chat/room/dto/response/RoomResponse.java
  backend/src/main/java/com/backend/domain/chat/room/entity/Room.java
  backend/src/main/java/com/backend/domain/chat/room/repository/RoomQueryRepository.java
  backend/src/main/java/com/backend/domain/chat/room/repository/RoomRepository.java
  backend/src/main/java/com/backend/domain/chat/room/repository/RoomRepositoryImpl.java
  backend/src/main/java/com/backend/domain/chat/room/service/RoomService.java
  backend/src/main/java/com/backend/domain/chat/room/service/RoomServiceImpl.java
  backend/src/main/java/com/backend/domain/fishingtrippost/repository/FishingTripPostQueryRepository.java
  backend/src/main/java/com/backend/domain/fishingtrippost/repository/FishingTripPostRepository.java
  backend/src/main/java/com/backend/domain/fishingtrippost/repository/FishingTripPostRepositoryImpl.java
  backend/src/main/java/com/backend/domain/fishingtriprecruitment/entity/FishingTripRecruitment.java
  backend/src/main/java/com/backend/domain/fishingtriprecruitment/repository/FishingTripRecruitmentQueryRepository.java
  backend/src/main/java/com/backend/domain/fishingtriprecruitment/repository/FishingTripRecruitmentRepository.java
  backend/src/main/java/com/backend/domain/fishingtriprecruitment/repository/FishingTripRecruitmentRepositoryImpl.java
  backend/src/main/java/com/backend/domain/member/repository/MemberQueryRepository.java
  backend/src/main/java/com/backend/domain/member/repository/MemberRepository.java
  backend/src/main/java/com/backend/domain/member/repository/MemberRepositoryImpl.java
  backend/src/main/java/com/backend/domain/member/service/MemberService.java
  backend/src/main/java/com/backend/domain/member/service/MemberServiceImpl.java
Labels: enhancement

#95 MIKKI-198
  backend/src/main/java/com/backend/domain/fishingtrippost/controller/FishingTripPostController.java
  backend/src/main/java/com/backend/domain/fishingtrippost/converter/FishingTripPostConverter.java
  backend/src/main/java/com/backend/domain/fishingtrippost/dto/request/FishingTripPostRequest.java
  backend/src/main/java/com/backend/domain/fishingtrippost/dto/response/FishingTripPostResponse.java
  backend/src/main/java/com/backend/domain/fishingtrippost/entity/FishingTripPost.java
  backend/src/main/java/com/backend/domain/fishingtrippost/repository/FishingTripPostJpaRepository.java
  backend/src/main/java/com/backend/domain/fishingtrippost/repository/FishingTripPostQueryRepository.java
  backend/src/main/java/com/backend/domain/fishingtrippost/repository/FishingTripPostRepository.java
  backend/src/main/java/com/backend/domain/fishingtrippost/repository/FishingTripPostRepositoryImpl.java
  backend/src/main/java/com/backend/domain/fishingtrippost/service/FishingTripPostService.java
  backend/src/main/java/com/backend/domain/fishingtrippost/service/FishingTripPostServiceImpl.java
  backend/src/main/java/com/backend/domain/fishingtriprecruitment/repository/FishingTripRecruitmentQueryRepository.java
  backend/src/test/java/com/backend/domain/fishingtrippost/controller/FishingTripPostControllerTest.java
  backend/src/test/java/com/backend/domain/fishingtrippost/repository/FishingTripPostRepositoryTest.java
  backend/src/test/java/com/backend/domain/fishingtrippost/service/FishingTripPostServiceTest.java
Labels: enhancement

#96 MIKKI-199
  backend/src/main/java/com/backend/domain/activityhistory/repository/ActivityHistoryQueryRepository.java
  backend/src/main/java/com/backend/domain/comment/repository/CommentQueryRepository.java
  backend/src/main/java/com/backend/domain/fishencyclopedia/repository/FishEncyclopediaQueryRepository.java
  backend/src/main/java/com/backend/domain/fishingtrippost/repository/FishingTripPostQueryRepository.java
  backend/src/main/java/com/backend/domain/fishingtrippost/service/FishingTripPostServiceImpl.java
  backend/src/main/java/com/backend/domain/fishingtriprecruitment/repository/FishingTripRecruitmentQueryRepository.java
  backend/src/main/java/com/backend/domain/fishingtriprecruitment/service/FishingTripRecruitmentServiceImpl.java
  backend/src/main/java/com/backend/domain/like/service/LikeServiceImpl.java
  backend/src/main/java/com/backend/domain/reservation/repository/ReservationQueryRepository.java
  backend/src/main/java/com/backend/domain/shipfishingpost/repository/ShipFishingPostQueryRepository.java
  backend/src/main/java/com/backend/global/util/QuerydslUtil.java
  backend/src/test/java/com/backend/domain/activityhistory/repository/ActivityHistoryRepositoryTest.java
  backend/src/test/java/com/backend/domain/fishingtrippost/repository/FishingTripPostRepositoryTest.java
  backend/src/test/java/com/backend/domain/shipfishingpost/repository/ShipFishingPostRepositoryTest.java
  backend/src/test/java/com/backend/domain/shipfishingpost/service/ShipFishingPostServiceTest.java
Labels: refactor

#98 MIKKI-189
  backend/src/main/java/com/backend/domain/chat/room/dto/response/RoomResponse.java
  backend/src/main/java/com/backend/domain/chat/room/entity/Room.java
  backend/src/main/java/com/backend/domain/chat/room/service/RoomServiceImpl.java
Labels: enhancement

#97 MIKKI-198
  backend/src/main/java/com/backend/domain/fishingtriprecruitment/exception/FishingTripRecruitmentErrorCode.java
  backend/src/main/java/com/backend/domain/fishingtriprecruitment/repository/FishingTripRecruitmentJpaRepository.java
  backend/src/main/java/com/backend/domain/fishingtriprecruitment/repository/FishingTripRecruitmentRepository.java
  backend/src/main/java/com/backend/domain/fishingtriprecruitment/repository/FishingTripRecruitmentRepositoryImpl.java
  backend/src/main/java/com/backend/domain/fishingtriprecruitment/service/FishingTripRecruitmentServiceImpl.java
  backend/src/test/java/com/backend/domain/fishingtriprecruitment/repository/FishingTripRecruitmentRepositoryTest.java
  backend/src/test/java/com/backend/domain/fishingtriprecruitment/service/FishingTripRecruitmentServiceTest.java
Labels: enhancement

#99 MIKKI-204
  backend/src/main/java/com/backend/domain/fishingtrippost/converter/FishingTripPostConverter.java
  backend/src/main/java/com/backend/domain/fishingtrippost/dto/response/FishingTripPostResponse.java
  backend/src/main/java/com/backend/domain/fishingtrippost/service/FishingTripPostServiceImpl.java
  backend/src/test/java/com/backend/domain/fishingtrippost/controller/FishingTripPostControllerTest.java
  backend/src/test/java/com/backend/domain/fishingtrippost/repository/FishingTripPostRepositoryTest.java
  backend/src/test/java/com/backend/domain/fishingtrippost/service/FishingTripPostServiceTest.java
Labels: enhancement

#100 MIKKI-203
  backend/src/main/java/com/backend/domain/fishingtrippost/controller/FishingTripPostController.java
  backend/src/main/java/com/backend/domain/fishingtrippost/converter/FishingTripPostConverter.java
  backend/src/main/java/com/backend/domain/fishingtrippost/dto/response/FishingTripPostResponse.java
  backend/src/main/java/com/backend/domain/fishingtrippost/service/FishingTripPostService.java
  backend/src/main/java/com/backend/domain/fishingtrippost/service/FishingTripPostServiceImpl.java
  backend/src/main/java/com/backend/domain/like/converter/LikeConverter.java
  backend/src/main/java/com/backend/domain/like/dto/response/LikeResponse.java
  backend/src/main/java/com/backend/domain/like/repository/LikeJpaRepository.java
  backend/src/main/java/com/backend/domain/like/repository/LikeQueryRepository.java
  backend/src/main/java/com/backend/domain/like/repository/LikeRepository.java
  backend/src/main/java/com/backend/domain/like/repository/LikeRepositoryImpl.java
  backend/src/main/java/com/backend/domain/like/scheduler/LikeCleanUpScheduler.java
  backend/src/main/java/com/backend/domain/like/scheduler/LikeSyncScheduler.java
  backend/src/main/java/com/backend/domain/like/service/LikeCacheService.java
  backend/src/main/java/com/backend/domain/like/service/LikeServiceImpl.java
  backend/src/main/java/com/backend/global/util/RedisUtil.java
  backend/src/test/java/com/backend/domain/fishingtrippost/controller/FishingTripPostControllerTest.java
  backend/src/test/java/com/backend/domain/fishingtrippost/service/FishingTripPostServiceTest.java
  backend/src/test/java/com/backend/domain/like/repository/LikeRepositoryTest.java
Labels: enhancement, refactor

#101 MIKKI-189
  backend/src/main/java/com/backend/domain/chat/controller/ChatController.java
  backend/src/main/java/com/backend/domain/chat/message/converter/MessageConverter.java
  backend/src/main/java/com/backend/domain/chat/message/dto/response/MessageResponse.java
  backend/src/main/java/com/backend/domain/chat/message/service/MessageService.java
  backend/src/main/java/com/backend/domain/chat/message/service/MessageServiceImpl.java
Labels: enhancement

#103 MIKKI-224
  backend/src/main/java/com/backend/domain/fishingtrippost/service/FishingTripPostServiceImpl.java
Labels: enhancement

#102 MIKKI-189
  backend/src/main/java/com/backend/domain/chat/message/converter/MessageConverter.java
  backend/src/main/java/com/backend/domain/chat/message/dto/response/MessageResponse.java
  backend/src/main/java/com/backend/domain/chat/message/service/MessageServiceImpl.java
  backend/src/main/java/com/backend/global/config/WebSocketConfig.java
Labels: bug

#104 MIKKI-224
  backend/src/main/java/com/backend/domain/fishingtrippost/repository/FishingTripPostQueryRepository.java
Labels: bug

#105 MIKKI-224
  backend/src/main/java/com/backend/domain/fishingtrippost/controller/FishingTripPostController.java
Labels: bug

#106 MIKKI-224
  backend/src/main/java/com/backend/domain/shipfishingpost/controller/ShipFishingPostController.java
  backend/src/main/java/com/backend/global/config/SecurityConfig.java
Labels: bug

#107 MIKKI-225
  backend/src/main/java/com/backend/domain/fishingtrippost/converter/FishingTripPostConverter.java
  backend/src/main/java/com/backend/domain/fishingtrippost/service/FishingTripPostServiceImpl.java
  backend/src/main/java/com/backend/domain/like/scheduler/LikeSyncScheduler.java
  backend/src/main/java/com/backend/domain/like/service/LikeCacheService.java
  backend/src/main/java/com/backend/domain/like/service/LikeServiceImpl.java
  backend/src/main/java/com/backend/global/util/CookieUtil.java
  backend/src/main/java/com/backend/global/util/RedisUtil.java
  backend/src/test/java/com/backend/domain/chat/room/service/RoomServiceTest.java
  backend/src/test/java/com/backend/domain/fishingtrippost/repository/FishingTripPostRepositoryTest.java
Labels: bug, refactor

#108 MIKKI-229
  backend/src/main/java/com/backend/domain/fishingtrippost/repository/FishingTripPostQueryRepository.java
  backend/src/main/java/com/backend/domain/like/domain/LikeTargetType.java
  backend/src/main/java/com/backend/domain/like/dto/response/LikeResponse.java
  backend/src/main/java/com/backend/domain/like/repository/LikeQueryRepository.java
  backend/src/main/java/com/backend/domain/like/repository/LikeRepository.java
  backend/src/main/java/com/backend/domain/like/repository/LikeRepositoryImpl.java
  backend/src/main/java/com/backend/domain/like/scheduler/LikeSyncScheduler.java
  backend/src/main/java/com/backend/domain/like/service/LikeService.java
  backend/src/main/java/com/backend/domain/like/service/LikeServiceImpl.java
  backend/src/main/java/com/backend/domain/member/dto/MemberResponse.java
  backend/src/main/java/com/backend/domain/member/repository/MemberQueryRepository.java
  backend/src/main/java/com/backend/domain/shipfishingpost/repository/ShipFishingPostQueryRepository.java
  backend/src/main/java/com/backend/domain/shipfishingpost/repository/ShipFishingPostRepositoryImpl.java
  backend/src/main/java/com/backend/global/util/RedisUtil.java
Labels: refactor

#109 MIKKI-230
  backend/src/main/java/com/backend/domain/captain/dto/Response/CaptainResponse.java
  backend/src/main/java/com/backend/domain/captain/repository/CaptainQueryRepository.java
  backend/src/main/java/com/backend/domain/member/dto/MemberResponse.java
  backend/src/main/java/com/backend/domain/member/repository/MemberQueryRepository.java
Labels: enhancement

#111 MIKKI-228
  backend/src/main/java/com/backend/domain/comment/controller/CommentController.java
  backend/src/main/java/com/backend/domain/comment/repository/CommentQueryRepository.java
  backend/src/main/java/com/backend/global/config/SecurityConfig.java
Labels: bug

#112 MIKKI-228
  backend/src/main/java/com/backend/global/config/SecurityConfig.java
Labels: enhancement

#113 MIKKI-234
  backend/src/main/java/com/backend/domain/fishingtrippost/dto/response/FishingTripPostResponse.java
  backend/src/main/java/com/backend/domain/fishingtrippost/repository/FishingTripPostQueryRepository.java
  backend/src/main/java/com/backend/domain/fishingtrippost/service/FishingTripPostServiceImpl.java
  backend/src/test/java/com/backend/domain/fishingtrippost/controller/FishingTripPostControllerTest.java
Labels: enhancement

#116 MIKKI-238
  backend/src/main/java/com/backend/domain/fishingtrippost/converter/FishingTripPostConverter.java
  backend/src/main/java/com/backend/domain/fishingtrippost/dto/response/FishingTripPostResponse.java
Labels: enhancement

#118 MIKKI-240
  backend/src/main/java/com/backend/domain/fishingtrippost/converter/FishingTripPostConverter.java
  backend/src/main/java/com/backend/domain/fishingtrippost/dto/response/FishingTripPostResponse.java
  backend/src/main/java/com/backend/domain/fishingtrippost/repository/FishingTripPostQueryRepository.java
  backend/src/main/java/com/backend/domain/fishingtrippost/service/FishingTripPostServiceImpl.java
  backend/src/test/java/com/backend/domain/fishingtrippost/repository/FishingTripPostRepositoryTest.java
Labels: enhancement

#120 MIKKI-239
  backend/src/main/java/com/backend/domain/ship/converter/ShipConverter.java
  backend/src/main/java/com/backend/domain/ship/dto/request/ShipRequest.java
  backend/src/main/java/com/backend/domain/ship/dto/response/ShipResponse.java
  backend/src/main/java/com/backend/domain/ship/entity/Ship.java
  backend/src/main/java/com/backend/domain/ship/repository/ShipQueryRepository.java
  backend/src/main/java/com/backend/domain/ship/service/ShipServiceImpl.java
  backend/src/main/java/com/backend/domain/shipfishingpost/repository/ShipFishingPostQueryRepository.java
  backend/src/test/java/com/backend/domain/ship/controller/ShipControllerTest.java
  backend/src/test/java/com/backend/domain/ship/repository/ShipRepositoryTest.java
  backend/src/test/java/com/backend/domain/ship/service/ShipServiceTest.java
Labels: enhancement

#121 MIKKI-240
  backend/src/main/java/com/backend/domain/fishingtriprecruitment/exception/FishingTripRecruitmentErrorCode.java
  backend/src/main/java/com/backend/domain/fishingtriprecruitment/service/FishingTripRecruitmentServiceImpl.java
Labels: enhancement

#122 MIKKI-241
  backend/src/main/java/com/backend/domain/fishingtriprecruitment/exception/FishingTripRecruitmentErrorCode.java
  backend/src/main/java/com/backend/domain/fishingtriprecruitment/service/FishingTripRecruitmentServiceImpl.java
Labels: refactor
